Repository fluxninja/aperture, pull requests merged in 2022-09, with the labels that each got.

#285 Fix distcache memberlist
  pkg/distcache/provider.go
  tools/demo_app/app/app.go
Labels: size/XS

#286 Soft pod anti affinity for demo app
  manifests/charts/demo-app/templates/deployment.yaml
Labels: size/S

#287 Refactor OTEL config
  api/aperture/common/info/v1/info.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/info/v1/info.pb.go
  cmd/aperture-agent/agent.go
  cmd/aperture-controller/controller.go
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/config-swagger.yaml
  docs/gen/config/aperture-controller/swagger.md
  pkg/info/info.go
  pkg/net/listener/gmux.go
  pkg/net/listener/provider.go
  pkg/otel/config.go
  pkg/policies/controlplane/circuit-factory.go
  tools/load_generator/scenarios/load_test.js
Labels: size/XL

#289 Add wrapper around olric log
  pkg/distcache/olric-logwriter.go
  pkg/distcache/provider.go
  pkg/jobs/job-group.go
  pkg/policies/dataplane/actuators/rate/ratetracker/rate-tracker_test.go
Labels: size/M

#293 Workaround kubectl port-forward connectivity issues
  manifests/k8s/Tiltfile
  manifests/k8s/tilt/portforward.sh
Labels: size/L

#298 rename demo app services
  docs/content/concepts/policies/policy-blueprints.md
  manifests/k8s/Tiltfile
  manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
  manifests/k8s/tanka/lib/apps/demoapp/main.libsonnet
  manifests/k8s/tilt/portforward.sh
  pkg/flowcontrol/envoy/authz_test.go
  pkg/policies/controlplane/validator_test.go
  tools/load_generator/scenarios/load_test.js
Labels: size/L

#299 Improve panels in the playground grafana
  manifests/charts/istioconfig/values.yaml
  manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet
  manifests/k8s/tanka/jsonnetfile.lock.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
  pkg/flowcontrol/common/metrics.go
  pkg/metrics/schema.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
  tools/load_generator/scenarios/load_test.js
Labels: size/L

#300 auto timeouts
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  libsonnet/1.0/_gen/v1/scheduler.libsonnet
  libsonnet/1.0/_gen/v1/schedulerworkload.libsonnet
  manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet
  pkg/policies/controlplane/validator_test.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  tools/load_generator/scenarios/load_test.js
Labels: size/XL

#301 update blueprint jsonnet
  manifests/k8s/tanka/jsonnetfile.lock.json
Labels: size/S

#302 update blueprint
  manifests/k8s/tanka/jsonnetfile.lock.json
Labels: size/S

#303 Updated CircleCi to release docker hub images from main only
  .circleci/continue-workflows.yml
Labels: size/XS

#295 Add basic agent packaging flow
  .circleci/config.yml
  .gitignore
  manifests/k8s/tilt/portforward.sh
  nfpm.yaml
  packaging/aperture-agent.yaml
Labels: size/L

#294 Add Flow Label to concepts in docs
  api/aperture/common/labelmatcher/v1/labelmatcher.proto
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/cloud/plugin.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/fluxmeter.md
  docs/content/concepts/flow-control/label/classifier.md
  docs/content/concepts/flow-control/label/label.md
  docs/content/concepts/flow-control/selector.md
  docs/content/concepts/flow-control/service.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
Labels: size/L

#309 Fix libsonnet python scripts
  libsonnet/1.0/_gen/v1/languagev1ratelimiter.libsonnet
  libsonnet/scripts/jsonnet-lib-gen.py
Labels: size/XS

#312 Rename rate tracker files
  pkg/distcache/logwriter.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/actuators/rate/ratetracker/distcache-rate-tracker.go
  pkg/policies/dataplane/actuators/rate/ratetracker/rate-tracker_test.go
Labels: size/M

#313 add tilt to tools
  .tool-versions
  manifests/k8s/tanka/jsonnetfile.lock.json
Labels: size/S

#315 Update Playground docs and its link in README
  README.md
  playground/README.md
Labels: size/S

#308 Update README.md
  README.md
Labels: size/XS

#317 Fix tanka pre-commit hook
  .pre-commit-config.yaml
  playground/Tiltfile
  playground/scripts/portforward.sh
  playground/tanka/charts/.gitignore
  scripts/precommit/check_tanka_show.sh
Labels: size/S

#316 use official istio chart instead of getindata istio
  docs/content/setup/istio.md
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  playground/Tiltfile
  playground/tanka/chartfile.yaml
  playground/tanka/environments/tilt/apps/istio/mixins.libsonnet
  playground/tanka/lib/apps/istio/main.libsonnet
Labels: size/M

#318 Playground improvements
  .pre-commit-config.yaml
  certs/ca.crt
  certs/ca.key
  certs/ca.srl
  certs/ca_config.txt
  certs/config.txt
  certs/crt.pem
  certs/csr.csr
  certs/gen.sh
  certs/key.pem
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  docs/content/setup/installation/agent/daemonset.md
  docs/content/setup/installation/controller.md
  docs/content/setup/istio.md
  manifests/charts/agent/.helmignore
  manifests/charts/agent/Chart.lock
  manifests/charts/agent/Chart.yaml
  manifests/charts/agent/README.md
  manifests/charts/agent/files/aperture-agent-config.yaml
  manifests/charts/agent/files/aperture-controller-config.yaml
  manifests/charts/agent/templates/NOTES.txt
  manifests/charts/agent/templates/_helpers.tpl
  manifests/charts/agent/templates/agent-controller-deployment.yaml
  manifests/charts/agent/templates/agent-controller-secret-apikey.yaml
  manifests/charts/agent/templates/agent-daemonset.yaml
  manifests/charts/agent/templates/agent-secret-apikey.yaml
  manifests/charts/agent/templates/configmap.yaml
  manifests/charts/agent/templates/rbac.yaml
  manifests/charts/agent/templates/service.yaml
  manifests/charts/agent/templates/webhooks.yaml
  manifests/charts/agent/values.yaml
  manifests/charts/aperture-controller/values.yaml
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  manifests/charts/istioconfig/values.yaml
  operator/config/kustomization.yaml
  pkg/policies/controlplane/validator_test.go
  playground/README.md
  playground/Tiltfile
  playground/ctlptl-kind-config.yaml
  playground/kind-config.yaml
  playground/tanka/apps/aperture-agent/main.jsonnet
  playground/tanka/apps/aperture-agent/mixins.libsonnet
  playground/tanka/apps/aperture-controller/main.jsonnet
  playground/tanka/apps/aperture-controller/mixins.libsonnet
  playground/tanka/apps/aperture-grafana/dashboards/json-example.json
  playground/tanka/apps/aperture-grafana/main.jsonnet
  playground/tanka/apps/aperture-grafana/mixins.libsonnet
  playground/tanka/apps/bookinfo/main.jsonnet
  playground/tanka/apps/bookinfo/mixins.libsonnet
  playground/tanka/apps/demoapp/main.jsonnet
  playground/tanka/apps/demoapp/mixins.libsonnet
  playground/tanka/apps/istio/main.jsonnet
  playground/tanka/apps/istio/mixins.libsonnet
  playground/tanka/apps/k6-operator/main.jsonnet
  playground/tanka/environments/tilt/apps/aperture-agent/mixins.libsonnet
  playground/tanka/jsonnetfile.lock.json
  playground/tanka/lib/apps/aperture-agent/main.libsonnet
  playground/tanka/lib/apps/aperture-controller/main.libsonnet
Labels: size/XXL

#319 Cleanup charts
  .pre-commit-config.yaml
  Makefile
  manifests/charts/Makefile
  manifests/charts/README.md
  manifests/charts/aperture-agent/README.md
  manifests/charts/aperture-controller/README.md
  manifests/charts/istioconfig/Chart.yaml
  manifests/charts/istioconfig/README.md
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  manifests/charts/istioconfig/values.yaml
  playground/tanka/apps/istio/mixins.libsonnet
  playground/tanka/charts/bookinfo
  playground/tanka/charts/bookinfo/.helmignore
  playground/tanka/charts/bookinfo/Chart.yaml
  playground/tanka/charts/bookinfo/templates/_helpers.tpl
  playground/tanka/charts/bookinfo/templates/deployment.yaml
  playground/tanka/charts/bookinfo/templates/ingress.yaml
  playground/tanka/charts/bookinfo/templates/service.yaml
  playground/tanka/charts/bookinfo/templates/serviceaccount.yaml
  playground/tanka/charts/bookinfo/values.yaml
  playground/tanka/charts/demo-app
  playground/tanka/charts/demo-app/.helmignore
  playground/tanka/charts/demo-app/Chart.yaml
  playground/tanka/charts/demo-app/templates/_helpers.tpl
  playground/tanka/charts/demo-app/templates/deployment.yaml
  playground/tanka/charts/demo-app/templates/service.yaml
  playground/tanka/charts/demo-app/templates/serviceaccount.yaml
  playground/tanka/charts/demo-app/values.yaml
  scripts/precommit/generate_helm_readme.sh
Labels: size/L

#320 Update .helmignore
  playground/tanka/charts/bookinfo/.helmignore
Labels: size/M

#321 Fix missing helmignore
  playground/tanka/charts/bookinfo/.helmignore
Labels: size/S

#271 Add SpanStatusCode and Duration to Span attributes
  docs/content/setup/istio.md
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  pkg/metrics/schema.go
  pkg/otel/config.go
  pkg/otelcollector/consts.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/flux-meter.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_flux_meter.go
Labels: size/L

#326 Fixes for envoy filters
  manifests/charts/istioconfig/templates/envoy_filter.yaml
Labels: size/XS

#328 Add systemd service to package
  .github/CODEOWNERS
  nfpm.yaml
  packaging/aperture-agent.service
  packaging/aperture-agent.yaml
  packaging/post-install.sh
Labels: size/L

#332 Bring back v3 OTLP extension
  manifests/charts/istioconfig/templates/envoy_filter.yaml
Labels: size/XS

#331 Add protoc-gen-go-deepcopy plugin support to buf generate
  api/buf.gen.yaml
  api/gen/proto/go/aperture/common/config/v1/config_properties_wrapper_deepcopy.gen.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache_deepcopy.gen.go
  api/gen/proto/go/aperture/common/info/v1/info_deepcopy.gen.go
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher_deepcopy.gen.go
  api/gen/proto/go/aperture/common/peers/v1/peers_deepcopy.gen.go
  api/gen/proto/go/aperture/common/selector/v1/selector_deepcopy.gen.go
  api/gen/proto/go/aperture/common/status/v1/status_deepcopy.gen.go
  api/gen/proto/go/aperture/common/watchdog/v1/watchdog_deepcopy.gen.go
  api/gen/proto/go/aperture/flowcontrol/v1/envoy_deepcopy.gen.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol_deepcopy.gen.go
  api/gen/proto/go/aperture/openapiv2/v1/openapiv2_deepcopy.gen.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/decisions/v1/decisions_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/classifier_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  go.mod
Labels: size/XXL

#322 Contentjai
  docs/content/cloud/cloud.md
  docs/content/concepts/flow-control/actuators/actuators.md
  docs/content/concepts/policies/policies.md
Labels: size/S

#306 add helm lint in pre-check
  .pre-commit-config.yaml
  Makefile
  manifests/charts/Makefile
  scripts/precommit/helmlint.sh
Labels: size/M

#335 add pre-commit check for circleci files
  .pre-commit-config.yaml
Labels: size/XS

#327 feat: CI workflow for Helm release
  .circleci/config.yml
  .circleci/releases.yaml
  .circleci/scripts/helm_release.sh
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/XL

#337 Fixed pre-commit
  .pre-commit-config.yaml
  README.md
  operator/README.md
  pkg/otelcollector/loggingexporter/README.md
  pkg/otelcollector/rollupprocessor/README.md
  pkg/policies/dataplane/resources/classifier/extractors/README.md
Labels: size/L

#339 Link to official docs in README.md
  README.md
  docs/content/assets/img/oaa.jpg
  docs/content/assets/img/oaa.png
  docs/content/assets/img/oaadark.png
Labels: size/S

#340 Fix themes in GH mobile app
  README.md
Labels: size/XS

#338 Document Flow Classifier concept
  docs/Makefile
  docs/content/concepts/flow-control/actuators/rate-limiter.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/content/concepts/flow-control/label/classifier.md
  docs/content/concepts/flow-control/label/label.md
  docs/content/concepts/flow-control/selector.md
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/swagger.md
  docs/gen/policies/policy.md
Labels: size/XXL

#342 pre-commit: install tools
  .pre-commit-config.yaml
  scripts/precommit/install_tools.sh
Labels: size/S

#347 Playground docs
  api/buf.lock
  docs/content/concepts/flow-control/fluxmeter.md
  docs/content/concepts/flow-control/selector.md
  docs/content/setup/_category_.yml
  docs/content/setup/installation/agent/agent.md
  docs/content/setup/istio.md
  docs/content/setup/playground.md
Labels: size/L

#348 Use aperture's validator/defaults in operator
  .pre-commit-config.yaml
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  manifests/charts/aperture-agent/README.md
  manifests/charts/aperture-agent/templates/_helpers.tpl
  manifests/charts/aperture-agent/templates/agent.yaml
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/templates/_helpers.tpl
  manifests/charts/aperture-controller/templates/controller.yaml
  manifests/charts/aperture-controller/values.yaml
  operator/api/v1alpha1/agent_types.go
  operator/api/v1alpha1/common_types.go
  operator/api/v1alpha1/controller_types.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent_reconciler.go
  operator/controllers/configmaps_test.go
  operator/controllers/constants.go
  operator/controllers/controller_reconciler.go
  operator/controllers/suite_test.go
  pkg/agentinfo/agent-info.go
  pkg/config/config.go
  pkg/config/duration.go
  pkg/config/log.go
  pkg/discovery/kubernetes/provide.go
  pkg/discovery/static/provide.go
  pkg/distcache/provider.go
  pkg/etcd/client/client.go
  pkg/jobs/job-group.go
  pkg/jobs/job.go
  pkg/metrics/metrics.go
  pkg/net/grpc/client.go
  pkg/net/grpc/server.go
  pkg/net/grpcgateway/grpcgateway.go
  pkg/net/http/client.go
  pkg/net/http/proxy.go
  pkg/net/http/server.go
  pkg/net/listener/listener.go
  pkg/net/tlsconfig/client.go
  pkg/net/tlsconfig/server.go
  pkg/otel/config.go
  pkg/peers/peers.go
  pkg/plugins/plugin-registry.go
  pkg/policies/dataplane/actuators/rate/ratetracker/rate-tracker_test.go
  pkg/profilers/profilers.go
  pkg/prometheus/client.go
  pkg/watchdog/policy.go
  pkg/watchdog/zz_generated.deepcopy.go
  plugins/service/aperture-plugin-fluxninja/pluginconfig/pluginconfig.go
  plugins/service/aperture-plugin-sentry/sentry/sentry.go
Labels: size/XXL

#352 add back emit_defaults flag
  api/buf.gen.yaml
  api/gen/proto/go/aperture/common/config/v1/config_properties_wrapper.pb.json.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.json.go
  api/gen/proto/go/aperture/common/info/v1/info.pb.json.go
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.json.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.json.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.json.go
  api/gen/proto/go/aperture/common/status/v1/status.pb.json.go
  api/gen/proto/go/aperture/common/watchdog/v1/watchdog.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/v1/envoy.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.json.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.json.go
  api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
Labels: size/L

#197 update k8s deployment readme and add kind cluster script
  playground/README.md
  scripts/aperture_dev_cluster.sh
Labels: size/L

#349 Fixe ratelimiter decision sync
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  go.mod
  pkg/config/koanf-unmarshaller.go
  pkg/flowcontrol/common/flowcontrol.go
  pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/iface/limiter.go
  pkg/policies/mocks/mock_limiter.go
Labels: size/L

#354 Fix broken generated controller documentation
  .circleci/continue-workflows.yml
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/swagger.md
  docs/gen/policies/policy.md
  docs/tools/swagger/swagger-templates/config.gotmpl
Labels: size/XL

#356 Fix heading ids in generated docs
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/concepts/flow-control/actuators/rate-limiter.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/content/concepts/flow-control/label/classifier.md
  docs/content/concepts/flow-control/label/label.md
  docs/content/concepts/flow-control/selector.md
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/swagger.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  docs/tools/swagger/swagger-templates/config.gotmpl
Labels: size/L

#358 Fixed missing API Key env variable
  manifests/charts/aperture-agent/templates/agent.yaml
  operator/controllers/utils.go
Labels: size/XS

#361 fix: release circleci filters
  .circleci/config.yml
Labels: size/XS

#363 Move aperture/helm releases back to setup config
  .circleci/config.yml
  .circleci/releases.yaml
Labels: size/L

#351 Update telemetry schema with workflows
  pkg/otelcollector/consts.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
Labels: size/M

#359 Replace tolerance with slope in Gradient Controller
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  libsonnet/1.0/_gen/v1/gradientcontroller.libsonnet
  pkg/policies/controlplane/component-factory_test.go
  pkg/policies/controlplane/components/controller/gradient.go
  pkg/policies/controlplane/validator_test.go
Labels: size/XXL

#368 Add new simplified architecture diagram
  docs/diagrams/architecture/aperture-k8s.mmd
  docs/diagrams/architecture/aperture-k8s.mmd.svg
  docs/diagrams/architecture/aperture.mmd
  docs/diagrams/architecture/aperture.mmd.svg
  docs/diagrams/architecture/fluxninja.mmd
  docs/diagrams/architecture/fluxninja.mmd.svg
Labels: size/S

#367 Use local IP address instead of hostname for forming olric cluster
  api/aperture/common/info/v1/info.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/info/v1/info.pb.go
  pkg/distcache/provider.go
  pkg/info/info.go
Labels: size/M

#366 Refactor various components
  .tool-versions
  api/aperture/policy/wrappers/v1/decisions.proto
  api/aperture/policy/wrappers/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/config/v1/config_properties_wrapper.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy_deepcopy.gen.go
  cmd/aperture-agent/agent.go
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/config-swagger.yaml
  docs/gen/config/aperture-controller/swagger.md
  docs/gen/policies/gen.yaml
  pkg/config/log.go
  pkg/distcache/provider.go
  pkg/filesystem/watcher/provider.go
  pkg/flowcontrol/common/flowcontrol_test.go
  pkg/k8s/provide.go
  pkg/net/grpc/client.go
  pkg/net/grpc/server.go
  pkg/net/grpcgateway/grpcgateway.go
  pkg/net/health/health.go
  pkg/net/http/client.go
  pkg/net/http/proxy.go
  pkg/net/http/server.go
  pkg/net/listener/provider.go
  pkg/net/tlsconfig/server.go
  pkg/peers/peers.go
  pkg/platform/platform.go
  pkg/plugins/plugin-registry.go
  pkg/policies/controlplane/components/actuators/concurrency/concurrency-limiter.go
  pkg/policies/controlplane/components/actuators/concurrency/load-shed-actuator.go
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
  pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
  pkg/policies/controlplane/policy-factory.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/provider.go
  pkg/policies/controlplane/resources/fluxmeter/flux-meter.go
  pkg/policies/dataplane/actuators/concurrency/auto-tokens.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/iface/limiter.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_limiter.go
  pkg/profilers/profilers.go
  pkg/prometheus/client.go
  pkg/watchdog/watchdog.go
  playground/tanka/jsonnetfile.lock.json
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
  plugins/service/aperture-plugin-sentry/main.go
  plugins/service/aperture-plugin-sentry/sentry/sentry.go
  test/aperture_suite_test.go
  tools/load_generator/scenarios/load_test.js
Labels: size/XXL

#370 fix logger
  Makefile
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/config-swagger.yaml
  docs/gen/config/aperture-controller/swagger.md
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/config/log.go
  pkg/config/zz_generated.deepcopy.go
  playground/tanka/apps/aperture-agent/mixins.libsonnet
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/L

#310 Add classifiers to flowcontrolv1.CheckResponse
  api/aperture/flowcontrol/v1/flowcontrol.proto
  api/aperture/policy/wrappers/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy_deepcopy.gen.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  libsonnet/1.0/_gen/v1/gen.libsonnet
  libsonnet/1.0/_gen/v1/policylanguagev1classifier.libsonnet
  pkg/flowcontrol/envoy/authz.go
  pkg/metrics/schema.go
  pkg/otelcollector/consts.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/controlplane/resources/classifier/classifier.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/iface/classifier.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/resources/classifier/classifier.go
  pkg/policies/dataplane/resources/classifier/provide.go
  pkg/policies/mocks/mock_engine.go
Labels: size/XXL

#360 Create remote repository tagging and protobuf pushing jobs
  .circleci/config.yml
  .circleci/post-release.yaml
Labels: size/L

#323 Response duration, FluxMeter attribute key, miscellaneous fixes
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/wrappers/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.go
  docs/content/setup/istio.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  libsonnet/1.0/_gen/v1/policylanguagev1fluxmeter.libsonnet
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/otel/config.go
  pkg/otelcollector/consts.go
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/enrichmentprocessor/processor.go
  pkg/otelcollector/enrichmentprocessor/processor_logs_test.go
  pkg/otelcollector/enrichmentprocessor/processor_metrics_test.go
  pkg/otelcollector/enrichmentprocessor/processor_traces_test.go
  pkg/otelcollector/helpers.go
  pkg/otelcollector/metricsprocessor/config.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/otelcollector/rollup.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/rollup.go
  pkg/otelcollector/rollupprocessor/rollup_processor.go
  pkg/otelcollector/rollupprocessor/rollup_processor_test.go
  pkg/policies/controlplane/resources/fluxmeter/flux-meter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/flux-meter.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_flux_meter.go
  pkg/profilers/profilers.go
  pkg/utils/helpers.go
  playground/README.md
Labels: size/XXL

#333 Add presentation layer for compiled circuit
  api/aperture/policy/language/v1/policy_view.proto
  api/gen/proto/go/aperture/policy/language/v1/policy_view.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy_view.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_view_deepcopy.gen.go
  go.mod
  go.sum
  pkg/policies/controlplane/circuit.go
Labels: size/XL

#373 Fix FN plugin constructor params
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/XS

#374 Corrected some of the links in the docs
  api/aperture/policy/language/v1/fluxmeter.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  docs/content/get-started/_category_.yml
  docs/content/get-started/installation/_category_.yml
  docs/content/get-started/installation/agent/_category_.yml
  docs/content/get-started/installation/agent/agent.md
  docs/content/get-started/installation/agent/kubernetes/_category_.yml
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  docs/content/get-started/istio.md
  docs/content/get-started/playground.md
  docs/content/get-started/supported-platforms.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
Labels: size/M

#379 check for the helm chart release tag
  .circleci/scripts/helm_release.sh
Labels: size/XS

#383 Fix sleep reference error in load test scenario
  tools/load_generator/scenarios/load_test.js
Labels: size/XS

#384 Fix pre-commit issue on main
  api/buf.lock
  docs/diagrams/architecture/aperture-k8s.mmd.svg
  docs/diagrams/architecture/fluxninja.mmd.svg
  docs/diagrams/ratelimit/ratelimit.mmd.svg
  docs/diagrams/traffic-flow/traffic.mmd.svg
Labels: size/S

#381 Expand top-level Flow Control concept
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/label/classifier.md
  docs/content/concepts/flow-control/label/label.md
Labels: size/L

#377 Clarify that pushing baggage to cloud is intended
  docs/content/concepts/flow-control/label/label.md
Labels: size/XS

#385 extract compiler to a separate package for classifiers
  docs/gen/config/aperture-controller/config-swagger.yaml
  docs/gen/config/aperture-controller/swagger.md
  pkg/flowcontrol/envoy/baggage/baggage.go
  pkg/flowcontrol/envoy/baggage/baggage_suite_test.go
  pkg/policies/controlplane/validator.go
  pkg/policies/dataplane/resources/classifier/classifier.go
  pkg/policies/dataplane/resources/classifier/classifier_test.go
  pkg/policies/dataplane/resources/classifier/compiler/compiler.go
Labels: size/XL

#380 Rename request flow labels according to OTEL semantic conventions
  docs/content/concepts/flow-control/label/classifier.md
  docs/content/concepts/flow-control/label/label.md
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/policies/controlplane/validator_test.go
  pkg/selectors/labels.go
  pkg/selectors/labels_test.go
  pkg/selectors/selectors_suite_test.go
  playground/tanka/apps/demoapp/mixins.libsonnet
Labels: size/L

#382 Fixed dead links in the docs
  docs/content/cloud/plugin.md
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/playground.md
Labels: size/S

#387 Add classifiers to playground
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/policy.proto
  api/buf.gen.yaml
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.json.go
  api/gen/proto/go/aperture/common/info/v1/info.pb.json.go
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.json.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.json.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.json.go
  api/gen/proto/go/aperture/common/status/v1/status.pb.json.go
  api/gen/proto/go/aperture/common/watchdog/v1/watchdog.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/v1/envoy.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.json.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.json.go
  api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_view.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.json.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  go.mod
  pkg/peers/peers.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/provider.go
  pkg/policies/dataplane/resources/classifier/classifier_test.go
  pkg/policies/dataplane/resources/classifier/compiler/compiler.go
  pkg/selectors/selector.go
  playground/tanka/apps/demoapp/mixins.libsonnet
  playground/tanka/jsonnetfile.lock.json
  tools/load_generator/scenarios/load_test.js
Labels: size/XXL

#388 Bump olric to v0.4.7 from patch version
  go.mod
  go.sum
Labels: size/XS

#390 add filter to auto token queries
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
  playground/tanka/apps/demoapp/mixins.libsonnet
  playground/tanka/jsonnetfile.lock.json
  tools/load_generator/scenarios/load_test.js
Labels: size/S

#389 add playground updated content to the docs section
  docs/content/get-started/playground.md
  playground/README.md
Labels: size/L

#393 Fixed YAML rendering issue for lists in charts
  manifests/charts/aperture-agent/templates/agent.yaml
  manifests/charts/aperture-controller/templates/controller.yaml
Labels: size/XS

#391 Fail classifier compilation on invalid flow label names
  docs/content/concepts/flow-control/label/classifier.md
  pkg/policies/controlplane/validator_test.go
  pkg/policies/dataplane/resources/classifier/classifier_test.go
  pkg/policies/dataplane/resources/classifier/compiler/compiler.go
  pkg/policies/dataplane/resources/classifier/extractors/compile.go
  playground/tanka/apps/demoapp/mixins.libsonnet
Labels: size/M

#392 Updated installation docs, playground docs and pullPolicy in charts
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  docs/content/get-started/playground.md
  docs/content/get-started/supported-platforms.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-agent/README.md
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/values.yaml
Labels: size/XL

#399 Update Tilt config and blueprints
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
  playground/Tiltfile
  playground/browser/go.mod
  playground/browser/go.sum
  playground/browser/main.go
  playground/tanka/jsonnetfile.lock.json
  tools/load_generator/scenarios/load_test.js
Labels: size/L

#400 Document Actuators
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/concepts/flow-control/actuators/actuators.md
  docs/content/concepts/flow-control/actuators/concurrency-limiter.md
  docs/content/concepts/flow-control/actuators/rate-limiter.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/content/concepts/flow-control/label/label.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
Labels: size/L

#401 move generated config docs and mermaid to docs/content
  .pre-commit-config.yaml
  cmd/aperture-agent/agent.go
  cmd/aperture-controller/controller.go
  docs/Makefile
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/controller.md
  docs/content/reference/configuration/policies.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/agent/metadata
  docs/gen/config/controller/config-swagger.yaml
  docs/gen/config/controller/metadata
  docs/gen/policies/config-swagger.yaml
  docs/gen/policies/gen.yaml
  docs/gen/policies/metadata
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/values.yaml
Labels: size/L

#398 Update README.md
  README.md
Labels: size/XS

#402 update docusaurus and add gh dark theme css
  docs/content/assets/img/active-flow-control-dark.png
  docs/content/assets/img/active-flow-control.jpg
  docs/content/assets/img/active-flow-control.png
  docs/content/assets/img/architecture.png
  docs/content/assets/img/control-loop.svg
  docs/content/assets/img/flowchart.png
  docs/content/assets/img/no-flow-control-dark.png
  docs/content/assets/img/no-flow-control.jpg
  docs/content/assets/img/no-flow-control.png
  docs/content/introduction.md
Labels: size/XS

#403 Revamp concepts layout
  api/aperture/common/labelmatcher/v1/labelmatcher.proto
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/cloud/plugin.md
  docs/content/concepts/flow-control/actuators/actuators.md
  docs/content/concepts/flow-control/concurrency-limiter.md
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/rate-limiter.md
  docs/content/concepts/flow-control/selector/flow-label.md
  docs/content/concepts/flow-control/selector/selector.md
  docs/content/concepts/flow-control/selector/service.md
  docs/content/concepts/policy/circuit/actuators.md
  docs/content/concepts/policy/circuit/circuit.md
  docs/content/concepts/policy/circuit/controllers.md
  docs/content/concepts/policy/circuit/signal-processors.md
  docs/content/concepts/policy/circuit/sources.md
  docs/content/concepts/policy/policy.md
  docs/content/concepts/policy/resources.md
  docs/content/get-started/blueprints.md
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/policies.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/policies/gen.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  pkg/agentinfo/agent-info.go
  pkg/policies/controlplane/runtime/circuit.go
Labels: size/L

#405 small doc edits
  docs/content/cloud/cloud.md
  docs/content/developers/_category_.yml
  docs/content/developers/cla.md
  docs/content/sidebars.json
Labels: size/L

#406 Added pointer to install policy using blueprints under get started
  docs/content/get-started/installation/controller.md
Labels: size/XS

#408 change the chart version
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
Labels: size/XS

#407 Add screenshot and a few doc changes
  CONTRIBUTING.md
  README.md
  docs/content/assets/img/grafana_dashboard.png
  docs/content/get-started/playground.md
Labels: size/M

#409 Move screenshot to playground
  README.md
Labels: size/S

#411 PR template added
  .github/pull_request_template.md
Labels: size/S

#412 update grafana dashboard image
  docs/content/assets/img/grafana_dashboard.png
Labels: size/XS

#413 Updated policy link to the first page of policy section
  docs/content/get-started/installation/controller.md
Labels: size/XS

#396 Fix policy compiler
  pkg/policies/controlplane/circuit-factory.go
  pkg/policies/controlplane/circuit.go
Labels: size/S

#415 Fixed controller installation issues and updated docs
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  operator/controllers/agent_reconciler.go
  operator/controllers/controller_reconciler.go
Labels: size/L

#410 Concept Docs
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/selector/flow-label.md
  docs/content/concepts/policy/circuit.md
  docs/content/concepts/policy/circuit/actuators.md
  docs/content/concepts/policy/circuit/circuit.md
  docs/content/concepts/policy/circuit/controllers.md
  docs/content/concepts/policy/circuit/signal-processors.md
  docs/content/concepts/policy/circuit/sources.md
  docs/content/concepts/policy/policy.md
  docs/content/concepts/policy/resources.md
  docs/content/get-started/blueprints.md
  docs/content/get-started/installation/agent/envoy/_category_.yml
  docs/content/get-started/installation/agent/envoy/istio.md
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/playground.md
  docs/content/reference/configuration/policies.md
  docs/gen/policies/gen.yaml
  manifests/charts/istioconfig/templates/envoy_filter.yaml
Labels: size/L

#414 Update Flow Control docs
  .prettierrc
  api/aperture/common/labelmatcher/v1/labelmatcher.proto
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/Makefile
  docs/content/cloud/plugin.md
  docs/content/concepts/flow-control/concurrency-limiter.md
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/rate-limiter.md
  docs/content/concepts/flow-control/selector/selector.md
  docs/content/concepts/flow-control/selector/service.md
  docs/content/reference/configuration/policies.md
  docs/gen/policies/gen.yaml
  pkg/selectors/labels.go
Labels: size/L

#416 add icon for charts.yaml file
  docs/content/assets/img/FluxNinja--main--logo--ICON.svg
Labels: size/XS

#417 Fix typos and add backlinks to Policy concept docs
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/selector/selector.md
  docs/content/concepts/policy/circuit.md
  docs/content/concepts/policy/resources.md
  docs/content/get-started/blueprints.md
  docs/content/reference/configuration/policies.md
  docs/gen/policies/gen.yaml
Labels: size/L

#419 Fix float parse warning
  pkg/otelcollector/metricsprocessor/processor.go
Labels: size/XS

#421 first helm version release chart changes
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#424 make k6 start after controller has started
  .github/pull_request_template.md
  playground/Tiltfile
Labels: size/XS

#426 Update README.md
  README.md
Labels: size/XS

#425 Doc fixes
  api/aperture/common/selector/v1/selector.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  docs/content/concepts/flow-control/concurrency-limiter.md
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/rate-limiter.md
  docs/content/concepts/flow-control/selector.md
  docs/content/concepts/service.md
  docs/content/get-started/playground.md
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/policies.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/policies/gen.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  pkg/agentinfo/agent-info.go
Labels: size/L

#428 Fix typos in docs
  README.md
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/concepts/policy/circuit.md
  docs/content/concepts/service.md
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/controller.md
  docs/content/reference/configuration/policies.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  docs/gen/policies/gen.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/net/listener/listener.go
Labels: size/M

#429 Fix typos
  docs/content/get-started/blueprints.md
  pkg/config/koanf-unmarshaller_test.go
Labels: size/S

#427 add pre-commit hook for codespell
  .pre-commit-config.yaml
  api/aperture/policy/language/v1/fluxmeter.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  docs/content/reference/configuration/policies.md
  docs/gen/policies/gen.yaml
Labels: size/S

#431 fix typos suggested by codespell
  .pre-commit-config.yaml
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd
  docs/content/assets/diagrams/traffic-flow/traffic.mmd
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  libsonnet/README.md
  manifests/charts/aperture-agent/README.md
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/values.yaml
  operator/README.md
  operator/api/v1alpha1/common_types.go
  operator/controllers/agent_hook.go
  operator/controllers/agent_hook_test.go
  operator/controllers/controller_hook.go
  operator/controllers/controller_hook_test.go
  operator/controllers/mutating_webhook_handler.go
  operator/controllers/utils_test.go
  pkg/config/defaults.go
  pkg/config/fxlogger.go
  pkg/config/koanf-unmarshaller.go
  pkg/filesystem/fileinfo.go
  pkg/multimatcher/multimatcher.go
  pkg/otelcollector/loggingexporter/factory_test.go
  pkg/otelcollector/rollupprocessor/rollup.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/resources/classifier/classifier_test.go
  pkg/policies/dataplane/resources/classifier/extractors/helpers.go
  pkg/selectors/selector.go
  playground/Tiltfile
  tools/demo_app/README.md
Labels: size/M

#430 Doc edits
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/controller.md
Labels: size/XS

#432 generate new mermaid diagrams
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
Labels: size/S

#433 fix typos suggested by codespell
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  pkg/otelcollector/rollup.go
Labels: size/XS

#435 Use markdown syntax to display playground image
  README.md
Labels: size/XS

#436 tweak blueprint docs
  docs/content/get-started/blueprints.md
Labels: size/S

#437 More blueprint fixes
  docs/content/get-started/blueprints.md
Labels: size/S

#446 Add FN plugin OTEL tests
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_suite_test.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/L

#445 Remove the Objects Index from generated docs
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/controller.md
  docs/content/reference/configuration/policies.md
  docs/gen/config/agent/metadata
  docs/gen/config/controller/metadata
  docs/gen/policies/metadata
  docs/tools/swagger/swagger-templates/config.gotmpl
Labels: size/L

#386 Update prometheus metrics names
  pkg/flowcontrol/common/metrics.go
  pkg/metrics/schema.go
  pkg/net/http/server.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
Labels: size/M

#420 Tweak Sentry plugin parsing log event and clean up
  plugins/service/aperture-plugin-sentry/main.go
  plugins/service/aperture-plugin-sentry/sentry/sentry.go
  plugins/service/aperture-plugin-sentry/sentry/sentrywriter.go
Labels: size/M

#450 Do not bring up platform in plugin UT
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
Labels: size/S

#454 Update blueprints
  playground/tanka/jsonnetfile.lock.json
Labels: size/S

#455 Move circuit-generator to cmd directory
  cmd/circuit-generator/main.go
Labels: size/M

#453 Fix typo in LoadShedDecisionWrapper
  .github/CODEOWNERS
  .github/pull_request_template.md
  README.md
  api/aperture/policy/wrappers/v1/decisions.proto
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions_deepcopy.gen.go
  cmd/circuit-generator/main.go
  docs/content/get-started/playground.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/aperture-plugin-fluxninja/plugin-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  go.mod
  operator/controllers/agent_hook.go
  operator/controllers/agent_reconciler.go
  operator/controllers/controller_hook.go
  operator/controllers/controller_reconciler.go
  operator/controllers/suite_test.go
  pkg/config/defaults.go
  pkg/config/defaults_test.go
  pkg/config/duration.go
  pkg/config/koanf-unmarshaller.go
  pkg/config/koanf-unmarshaller_test.go
  pkg/config/timestamp.go
  pkg/config/validator.go
  pkg/policies/controlplane/components/actuators/concurrency/load-shed-actuator.go
  pkg/policies/controlplane/provider.go
  pkg/policies/controlplane/validator.go
  pkg/policies/controlplane/validator_test.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
  pkg/policies/dataplane/resources/classifier/extractors/extractors_suite_test.go
Labels: size/XL

#461 Fix test
  operator/controllers/suite_test.go
Labels: size/XS

#464 Fossa circleci
  .circleci/continue-workflows.yml
  README.md
Labels: size/M

#365 Add peers discovery, entity cache service methods
  api/aperture/common/entitycache/v1/entitycache.proto
  api/aperture/common/peers/v1/peers.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.gw.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.json.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache_deepcopy.gen.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache_grpc.pb.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.gw.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.json.go
  api/gen/proto/go/aperture/common/peers/v1/peers_deepcopy.gen.go
  api/gen/proto/go/aperture/common/peers/v1/peers_grpc.pb.go
  docs/gen/policies/gen.yaml
  pkg/distcache/service-discovery.go
  pkg/entitycache/cache_test.go
  pkg/entitycache/entity_cache-service.go
  pkg/entitycache/entity_cache.go
  pkg/flowcontrol/common/flowcontrol.go
  pkg/flowcontrol/common/flowcontrol_test.go
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/enrichmentprocessor/processor_logs_test.go
  pkg/otelcollector/enrichmentprocessor/processor_metrics_test.go
  pkg/otelcollector/enrichmentprocessor/processor_traces_test.go
  pkg/peers/peers-service.go
  pkg/peers/peers.go
  pkg/peers/peers_suite_test.go
  pkg/peers/peers_test.go
Labels: size/XXL

#448 Add tests for status pkg
  pkg/status/status_suite_test.go
  pkg/status/status_test.go
Labels: size/L

#375 Unify TLS config
  pkg/net/tlsconfig/server.go
  pkg/otel/config.go
Labels: size/L

#465 Fix TLS config
  pkg/otel/config.go
Labels: size/S

#470 fix docs makefile macos
  docs/Makefile
Labels: size/XS

#480 Disable ext_authz request body buffering by default
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/get-started/installation/agent/envoy/istio.md
  manifests/charts/istioconfig/templates/envoy_filter.yaml
Labels: size/S

#477 Update OTEL to 0.60.0
  go.mod
  go.sum
  pkg/otelcollector/enrichmentprocessor/processor.go
  pkg/otelcollector/loggingexporter/otlptext/databuffer.go
  pkg/otelcollector/loggingexporter/otlptext/logs.go
  pkg/otelcollector/loggingexporter/testdata/log.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/rollupprocessor/rollup_processor.go
  pkg/policies/controlplane/policy.go
Labels: size/M

#493 remove CertPath key from server TLS config
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/configmaps_test.go
  operator/controllers/controller_config_test.tpl
  operator/controllers/controller_reconciler.go
  pkg/net/tlsconfig/server.go
Labels: size/L

#497 Update accepted/incoming concurrency port names
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
Labels: size/XS

#484 Update README.md
  README.md
Labels: size/S

#498 rename some server tls config fields
  README.md
  docs/content/reference/configuration/agent.md
  docs/content/reference/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent_config_test.tpl
  operator/controllers/configmaps_test.go
  operator/controllers/controller_config_test.tpl
  operator/controllers/controller_reconciler.go
  pkg/net/tlsconfig/server.go
Labels: size/L

#472 Playground doc improvements
  README.md
  docs/content/assets/img/starttraffic.png
  docs/content/assets/img/starttrafficbig.png
  docs/content/get-started/playground.md
Labels: size/L

#508 Update playground docs
  docs/content/get-started/blueprints.md
  docs/content/get-started/playground.md
Labels: size/L

#501 Use interface for Reading, TickInfo in runtime package
  pkg/policies/controlplane/components/actuators/concurrency/load-shed-actuator.go
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
  pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
  pkg/policies/controlplane/components/arithmetic-combinator.go
  pkg/policies/controlplane/components/constant.go
  pkg/policies/controlplane/components/controller/controller-component.go
  pkg/policies/controlplane/components/controller/controller-state-read-api.go
  pkg/policies/controlplane/components/controller/controller.go
  pkg/policies/controlplane/components/controller/gradient.go
  pkg/policies/controlplane/components/controller/gradient_test.go
  pkg/policies/controlplane/components/decider.go
  pkg/policies/controlplane/components/decider_test.go
  pkg/policies/controlplane/components/ema.go
  pkg/policies/controlplane/components/ema_test.go
  pkg/policies/controlplane/components/extrapolator.go
  pkg/policies/controlplane/components/max.go
  pkg/policies/controlplane/components/min.go
  pkg/policies/controlplane/components/promql.go
  pkg/policies/controlplane/components/sqrt.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/reading/reading.go
  pkg/policies/controlplane/reading/reading_test.go
  pkg/policies/controlplane/runtime/circuit-api.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/controlplane/runtime/port-to-value.go
  pkg/policies/controlplane/runtime/reading.go
  pkg/policies/controlplane/runtime/reading_test.go
  pkg/policies/controlplane/runtime/runtime_suite_test.go
  pkg/policies/controlplane/runtime/tick-info.go
Labels: size/XL

#500 Documentation improvements
  .pre-commit-config.yaml
  README.md
  docs/Makefile
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/assets/gen/architecture_simple.mmd
  docs/content/assets/gen/architecture_simple.mmd.svg
  docs/content/assets/gen/flow-control.md_0.mmd
  docs/content/assets/gen/flow-control.md_0.mmd.svg
  docs/content/assets/gen/service.md_0.mmd
  docs/content/assets/gen/service.md_0.mmd.svg
  docs/content/assets/gen/service.md_1.mmd
  docs/content/assets/gen/service.md_1.mmd.svg
  docs/content/assets/gen/service.md_2.mmd
  docs/content/assets/gen/service.md_2.mmd.svg
  docs/content/cloud/plugin.md
  docs/content/introduction.md
  docs/tools/mermaid/md_to_mmd.sh
  docs/tools/mermaid/mermaid-theme.json
  scripts/precommit/generate_config_markdown.sh
  scripts/precommit/generate_docs.sh
  scripts/precommit/generate_mermaid.sh
  scripts/precommit/generate_swagger.sh
Labels: size/L

#510 fix mermaid generator on macOS
  docs/tools/mermaid/md_to_mmd.sh
Labels: size/S

#512 update mermaid theme
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/assets/gen/architecture_simple.mmd.svg
  docs/content/assets/gen/flow-control.md_0.mmd.svg
  docs/content/assets/gen/service.md_0.mmd.svg
  docs/content/assets/gen/service.md_1.mmd.svg
  docs/content/assets/gen/service.md_2.mmd.svg
  docs/tools/mermaid/mermaid-theme.json
Labels: size/S

#511 Peers package unit testing
  pkg/peers/peers_suite_test.go
  pkg/peers/peers_test.go
  pkg/status/status_suite_test.go
Labels: size/L

#514 add link to explainer video in readme
  README.md
  docs/content/assets/gen/architecture_simple.mmd
  docs/content/assets/gen/architecture_simple.mmd.svg
  docs/content/introduction.md
Labels: size/S

#519 Upgraded minimum Kubernetes version to 1.23
  docs/content/get-started/supported-platforms.md
Labels: size/XS

#475 Added details on how to provide custom config for Agent and Controller in docs
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
Labels: size/M

#520 Fix tests on main
  pkg/flowcontrol/envoy/authz_test.go
  pkg/flowcontrol/envoy/baggage/baggage_suite_test.go
  pkg/otelcollector/enrichmentprocessor/processor_metrics_test.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
Labels: size/M

#481 Split scraping metrics for FN plugin
  pkg/otel/config.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/L

#522 update envoy filter docs
  docs/content/get-started/installation/agent/envoy/istio.md
Labels: size/L

#525 Fixed typos in the installation docs
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
Labels: size/XS

#523 change chart version to v0.2.1
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#524 Change tool installation script directory
  .circleci/scripts/asdf_install.sh
  Makefile
  docs/content/get-started/playground.md
  playground/scripts/manage_tools.sh
Labels: size/S

#526 position change for installation and playground
  docs/content/get-started/installation/_category_.yml
  docs/content/get-started/playground.md
Labels: size/XS

#527 Update chart versions before v0.2.2 release
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#528 Fix Prometheus scrape config in OTEL
  go.mod
  pkg/otel/config.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/M
