Repository fluxninja/aperture, pull requests merged in 2022-10, with the labels that each got.

#648 Actions native Concurrency instead of Consecutiveness
  .github/workflows/issues-notion-sync.yml
Labels: size/S

#650 Upgraded chart versions to v0.4.0
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#651 Cherry-picked changes from main
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#624 using our own pre-commit repo for circleci
  .pre-commit-config.yaml
Labels: size/XS

#652 remove circleci pre-commit
  .pre-commit-config.yaml
Labels: size/XS

#614 Populate version in build
  .circleci/scripts/docker_build.sh
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  pkg/info/build.sh
Labels: size/S

#653 Cherry-picked latest changes from main
  .circleci/scripts/docker_build.sh
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  pkg/info/build.sh
Labels: size/S

#659 Fixed controller init container image issue
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/templates/controller.yaml
  manifests/charts/aperture-controller/values.yaml
Labels: size/M

#664 Updated PR template for blueprint changes
  .github/pull_request_template.md
Labels: size/XS

#661 Fixed the blueprint example
  docs/content/get-started/blueprints.md
Labels: size/XS

#672 jsonnet example validator
  .github/pull_request_template.md
  .pre-commit-config.yaml
  Makefile
  docs/Makefile
  docs/tools/mermaid/md_to_mmd.sh
  docs/tools/scripts/validate_jsonnet.sh
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  operator/config/samples/kustomization.yaml
  operator/hack/create_policy_sample.sh
  scripts/go_build.sh
  scripts/go_build_plugins.sh
  scripts/go_generate.sh
  scripts/go_generate_swagger.sh
  scripts/golangci_lint.sh
  scripts/install_go_tools.sh
  scripts/precommit/check-operator-spec.sh
  scripts/precommit/generate_api.sh
  scripts/precommit/generate_blueprints.sh
  scripts/precommit/generate_config_markdown.sh
  scripts/precommit/generate_helm_readme.sh
  scripts/precommit/generate_mermaid.sh
  scripts/precommit/generate_swagger.sh
  scripts/precommit/helmlint.sh
  scripts/precommit/install_tools.sh
Labels: size/XL

#679 Use FN OTEL loggingexporter
  cmd/aperture-agent/agent/otel-component.go
  go.mod
  go.sum
  pkg/otelcollector/consts.go
  pkg/otelcollector/loggingexporter/README.md
  pkg/otelcollector/loggingexporter/config.go
  pkg/otelcollector/loggingexporter/config_test.go
  pkg/otelcollector/loggingexporter/doc.go
  pkg/otelcollector/loggingexporter/factory.go
  pkg/otelcollector/loggingexporter/factory_test.go
  pkg/otelcollector/loggingexporter/logging_exporter.go
  pkg/otelcollector/loggingexporter/logging_exporter_test.go
  pkg/otelcollector/loggingexporter/otlptext/databuffer.go
  pkg/otelcollector/loggingexporter/otlptext/databuffer_test.go
  pkg/otelcollector/loggingexporter/otlptext/logs.go
  pkg/otelcollector/loggingexporter/otlptext/logs_test.go
  pkg/otelcollector/loggingexporter/otlptext/metrics.go
  pkg/otelcollector/loggingexporter/otlptext/metrics_test.go
  pkg/otelcollector/loggingexporter/otlptext/traces.go
  pkg/otelcollector/loggingexporter/otlptext/traces_test.go
  pkg/otelcollector/loggingexporter/testdata/common.go
  pkg/otelcollector/loggingexporter/testdata/config.yaml
  pkg/otelcollector/loggingexporter/testdata/log.go
  pkg/otelcollector/loggingexporter/testdata/metric.go
  pkg/otelcollector/loggingexporter/testdata/resource.go
  pkg/otelcollector/loggingexporter/testdata/trace.go
Labels: size/XXL

#675 generate mermaid for circuits
  api/buf.lock
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.dot
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.svg
  blueprints/scripts/generate_all.sh
  cmd/circuit-compiler/main.go
  pkg/policies/controlplane/circuit-graph.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XXL

#655 Create metrics for RateLimiter
  go.mod
  go.sum
  pkg/metrics/schema.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/limiter.go
  pkg/policies/dataplane/iface/rate-limiter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_limiter.go
Labels: size/XL

#689 Classification interfaces
  pkg/policies/dataplane/iface/classification-engine.go
  pkg/policies/dataplane/iface/classifier.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/resources/classifier/classification-engine.go
Labels: size/M

#692 Create ports in-place for better readability
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/L

#691 Refactor mermaid generator
  .gitignore
  .pre-commit-config.yaml
  README.md
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.png
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd.png
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd.png
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.png
  docs/content/assets/diagrams/ratelimit/ratelimit.mmd.svg
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.png
  docs/content/assets/diagrams/traffic-flow/traffic.mmd.svg
  docs/content/assets/gen/architecture_simple.mmd.png
  docs/content/assets/gen/architecture_simple.mmd.svg
  docs/content/assets/gen/flow-control.md_0.mmd.png
  docs/content/assets/gen/flow-control.md_0.mmd.svg
  docs/content/assets/gen/introduction/architecture_simple.mmd
  docs/content/assets/gen/introduction/architecture_simple.mmd.png
  docs/content/assets/gen/introduction/architecture_simple.mmd.svg
  docs/content/assets/gen/service.md_0.mmd.png
  docs/content/assets/gen/service.md_0.mmd.svg
  docs/content/assets/gen/service.md_1.mmd.png
  docs/content/assets/gen/service.md_1.mmd.svg
  docs/content/assets/gen/service.md_2.mmd.png
  docs/content/assets/gen/service.md_2.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_0.mmd
  docs/content/concepts/assets/gen/service/service.md_0.mmd.png
  docs/content/concepts/assets/gen/service/service.md_0.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_1.mmd
  docs/content/concepts/assets/gen/service/service.md_1.mmd.png
  docs/content/concepts/assets/gen/service/service.md_1.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_2.mmd
  docs/content/concepts/assets/gen/service/service.md_2.mmd.png
  docs/content/concepts/assets/gen/service/service.md_2.mmd.svg
  docs/content/concepts/flow-control/assets/gen/flow-control/flow-control.md_0.mmd
  docs/content/concepts/flow-control/assets/gen/flow-control/flow-control.md_0.mmd.png
  docs/content/concepts/flow-control/assets/gen/flow-control/flow-control.md_0.mmd.svg
  docs/tools/mermaid/md_to_mmd.sh
  docs/tools/scripts/validate_jsonnet.sh
Labels: size/M

#619 Split Port into InPort and OutPort
  .codespellignore
  .pre-commit-config.yaml
  api/aperture/policy/language/v1/policy.proto
  api/aperture/policy/language/v1/policy_view.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/policy_view.pb.go
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/blueprints/rate-limiter/README.md
  blueprints/blueprints/rate-limiter/config.libsonnet
  blueprints/blueprints/rate-limiter/example/example.jsonnet
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.dot
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.svg
  blueprints/blueprints/rate-limiter/example/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/inport.libsonnet
  blueprints/lib/1.0/_gen/v1/outport.libsonnet
  blueprints/lib/1.0/custom/port.libsonnet
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  blueprints/lib/1.0/policies/rate-limiter/rate-limiter.libsonnet
  blueprints/lib/1.0/spec.libsonnet
  blueprints/scripts/generate_all.sh
  docs/content/concepts/assets/gen/service/service.md_1.mmd
  docs/content/concepts/assets/gen/service/service.md_2.mmd
  docs/content/references/configuration/policies.md
  docs/gen/policies/gen.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/circuit-factory.go
  pkg/policies/controlplane/circuit-graph.go
  pkg/policies/controlplane/runtime/circuit.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XXL

#696 fix codespell issues
  docs/content/concepts/flow-control/flow-classifier.md
  pkg/flowcontrol/envoy/baggage/baggage.go
  pkg/otelcollector/config.go
  pkg/policies/controlplane/components/ema.go
Labels: size/S

#698 Fix missing log attributes
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
Labels: size/M

#700 Fix agent_group population in logs
  cmd/aperture-agent/agent/otel-component.go
Labels: size/XS

#701 Generate CRs for blueprints instead of raw policies
  .pre-commit-config.yaml
  Makefile
  blueprints/CONTRIBUTING.md
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/blueprints/latency-gradient/main.libsonnet
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.dot
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.svg
  blueprints/blueprints/rate-limiter/example/gen/policies/example.yaml
  blueprints/blueprints/rate-limiter/main.libsonnet
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  blueprints/lib/1.0/policies/rate-limiter/rate-limiter.libsonnet
  blueprints/scripts/aperture-generate.py
  blueprints/scripts/generate_all.sh
  cmd/circuit-compiler/main.go
  docs/Makefile
  docs/content/assets/gen/introduction/architecture_simple.mmd.png
  docs/content/assets/gen/introduction/architecture_simple.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_0.mmd.png
  docs/content/concepts/assets/gen/service/service.md_0.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_1.mmd.png
  docs/content/concepts/assets/gen/service/service.md_1.mmd.svg
  docs/content/concepts/assets/gen/service/service.md_2.mmd.png
  docs/content/concepts/assets/gen/service/service.md_2.mmd.svg
  docs/content/concepts/flow-control/assets/gen/flow-control/flow-control.md_0.mmd.png
  docs/content/concepts/flow-control/assets/gen/flow-control/flow-control.md_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.jsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0_spec.yaml
  docs/content/policies/blueprints.md
  docs/content/policies/tutorial/assets/gen/static-rate-limiting/jsonnet/static-rate-limiting_0.mmd.png
  docs/content/policies/tutorial/assets/gen/static-rate-limiting/jsonnet/static-rate-limiting_0.mmd.svg
  docs/content/policies/tutorial/assets/gen/static-rate-limiting/jsonnet/static-rate-limiting_0_spec.yaml
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.jsonnet
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.md5sum
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.png
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.svg
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.yaml
  docs/content/policies/tutorial/static-rate-limiting.md
  docs/tools/jsonnet/generate_jsonnet.sh
  docs/tools/mermaid/generate_mermaid.sh
  go.mod
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  operator/hack/create_policy_sample.sh
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XXL

#654 Olric Metrics
  pkg/distcache/olric-metrics.go
  pkg/distcache/provider.go
  pkg/metrics/schema.go
Labels: size/L

#708 fix tanka show pre-commit hook
  docs/content/policies/blueprints.md
  scripts/precommit/check_tanka_show.sh
Labels: size/XS

#709 Use term DistCache instead of Olric
  pkg/distcache/distcache-metrics.go
  pkg/distcache/olric-metrics.go
  pkg/distcache/provider.go
  pkg/metrics/schema.go
Labels: size/L

#711 dive into slices for validation
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  go.mod
  go.sum
  pkg/config/validator.go
  pkg/config/validator_test.go
  pkg/policies/controlplane/validator.go
Labels: size/M

#710 Move Selector one level above from Scheduler to ConcurrencyLimiter
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/concurrencylimiter.libsonnet
  blueprints/lib/1.0/_gen/v1/scheduler.libsonnet
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  docs/content/references/configuration/policies.md
  docs/gen/policies/gen.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/config/validator.go
  pkg/policies/controlplane/components/actuators/concurrency/concurrency-limiter.go
  pkg/policies/controlplane/validator_test.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
Labels: size/XL

#712 remove redundant logs
  pkg/config/validator.go
Labels: size/XS

#714 Replace Configuration with Controller CRD section
  docs/content/get-started/installation/controller.md
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/S

#676 Wavepool generator in playground
  docs/content/assets/img/starttraffic.png
  docs/content/assets/img/starttrafficbig.png
  docs/content/assets/img/stop-traffic.png
  docs/content/get-started/playground.md
  playground/Tiltfile
  playground/load_generator/scenarios/demoapp-load-test-cr.yaml
  playground/tanka/apps/demoapp/mixins.libsonnet
  playground/tanka/apps/k6-operator/main.jsonnet
  playground/tanka/lib/apps/k6-operator/k6/certmanager/certificate.yaml
  playground/tanka/lib/apps/k6-operator/k6/certmanager/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/certmanager/kustomizeconfig.yaml
  playground/tanka/lib/apps/k6-operator/k6/crd/bases/k6.io_k6s.yaml
  playground/tanka/lib/apps/k6-operator/k6/crd/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/crd/kustomizeconfig.yaml
  playground/tanka/lib/apps/k6-operator/k6/crd/patches/cainjection_in_k6s.yaml
  playground/tanka/lib/apps/k6-operator/k6/crd/patches/webhook_in_k6s.yaml
  playground/tanka/lib/apps/k6-operator/k6/default/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/default/manager_auth_proxy_patch.yaml
  playground/tanka/lib/apps/k6-operator/k6/default/manager_webhook_patch.yaml
  playground/tanka/lib/apps/k6-operator/k6/default/webhookcainjection_patch.yaml
  playground/tanka/lib/apps/k6-operator/k6/manager/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/manager/manager.yaml
  playground/tanka/lib/apps/k6-operator/k6/manifests/bases/operator.clusterserviceversion.yaml
  playground/tanka/lib/apps/k6-operator/k6/manifests/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/prometheus/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/prometheus/monitor.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/auth_proxy_client_clusterrole.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/auth_proxy_role.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/auth_proxy_role_binding.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/auth_proxy_service.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/k6_editor_role.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/k6_viewer_role.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/leader_election_role.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/leader_election_role_binding.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/role.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/role_binding.yaml
  playground/tanka/lib/apps/k6-operator/k6/rbac/service_account.yaml
  playground/tanka/lib/apps/k6-operator/k6/samples/k6_v1alpha1_configmap.yaml
  playground/tanka/lib/apps/k6-operator/k6/samples/k6_v1alpha1_k6.yaml
  playground/tanka/lib/apps/k6-operator/k6/samples/k6_v1alpha1_k6_with_localfile.yaml
  playground/tanka/lib/apps/k6-operator/k6/samples/k6_v1alpha1_k6_with_output.yaml
  playground/tanka/lib/apps/k6-operator/k6/samples/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/scorecard/bases/config.yaml
  playground/tanka/lib/apps/k6-operator/k6/scorecard/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/scorecard/patches/basic.config.yaml
  playground/tanka/lib/apps/k6-operator/k6/scorecard/patches/olm.config.yaml
  playground/tanka/lib/apps/k6-operator/k6/webhook/kustomization.yaml
  playground/tanka/lib/apps/k6-operator/k6/webhook/kustomizeconfig.yaml
  playground/tanka/lib/apps/k6-operator/k6/webhook/service.yaml
  playground/tanka/lib/apps/k6-operator/main.libsonnet
Labels: size/XXL

#697 Add Aperture SDK examples
  playground/Tiltfile
  playground/tanka/apps/aperture-go-example/main.jsonnet
  playground/tanka/apps/aperture-go-example/mixins.libsonnet
  playground/tanka/apps/aperture-java-example/main.jsonnet
  playground/tanka/apps/aperture-java-example/mixins.libsonnet
  playground/tanka/lib/apps/aperture-sdk-example/aperture-sdk-example.libsonnet
  playground/tanka/lib/apps/aperture-sdk-example/main.libsonnet
  playground/tanka/lib/k.libsonnet
Labels: size/L

#690 Use monikers instead of UUID for controllerID
  go.mod
  go.sum
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Labels: size/XS

#688 Update otel collector fork (istio 1.15 compat hack)
  docs/content/get-started/installation/agent/envoy/istio.md
  docs/content/get-started/installation/agent/supported-platforms.md
  go.mod
  go.sum
Labels: size/S

#717 v0.5.0 Release
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#722 add operator dependencies to tools.go
  .circleci/continue-workflows.yml
  Makefile
  go.mod
  go.sum
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/config/crd/bases/fluxninja.com_policies.yaml
  pkg/tools/tools.go
Labels: size/M

#721 Policy heartbeats
  .github/pull_request_template.md
  Makefile
  api/aperture/plugins/fluxninja/v1/heartbeat.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.gw.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/policy_grpc.pb.go
  docs/gen/policies/gen.yaml
  pkg/policies/controlplane/components/promql.go
  pkg/policies/controlplane/policy-factory.go
  pkg/policies/controlplane/policy-service.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
Labels: size/XXL

#724 Circuit Compiler - Mermaid improvements
  .circleci/config.yml
  .circleci/continue-workflows.yml
  api/aperture/policy/language/v1/policy_view.proto
  api/gen/proto/go/aperture/policy/language/v1/policy_view.pb.go
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.jsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  docs/content/policies/blueprints.md
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.jsonnet
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.md5sum
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.png
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.mmd.svg
  docs/content/policies/tutorial/assets/static-rate-limiting/static-rate-limiting.yaml
  docs/content/policies/tutorial/static-rate-limiting.md
  docs/tools/jsonnet/generate_jsonnet.sh
  docs/tools/mermaid/mermaid-theme.json
  docs/tools/mermaid/mermaid.css
  pkg/policies/controlplane/circuit-graph.go
Labels: size/XXL

#726 Stage aperture.swagger.yaml in docs dir
  .github/pull_request_template.md
  Makefile
  api/Makefile
  blueprints/Makefile
  blueprints/lib/README.md
  docs/Makefile
  docs/content/assets/openapiv2/aperture.swagger.yaml
Labels: size/S

#727 circleci: set GOMAXPROCS using enviornment instead of BASH_ENV
  .circleci/continue-workflows.yml
Labels: size/S

#728 precommit: do not pass filenames to check operator spec step
  .pre-commit-config.yaml
Labels: size/XS

#730 Scheduler and Controller window match fix
  blueprints/blueprints/latency-gradient/config.libsonnet
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket-load-shed.go
Labels: size/XL

#732 Manual mode for controller and other fixes
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/lib/1.0/_gen/v1/controllerdynamicconfig.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/gradientcontroller.libsonnet
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/references/configuration/policies.md
  docs/gen/policies/gen.yaml
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/controlplane/components/controller/controller-component.go
  pkg/policies/controlplane/components/controller/gradient.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/controlplane/validator.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket-load-shed.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq_test.go
  pkg/policies/dataplane/iface/classification-engine.go
  pkg/policies/dataplane/resources/classifier/classification-engine.go
  pkg/policies/mocks/mock_classification_engine.go
Labels: size/XXL

#738 Fix missing policy factory pointer for agent
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
Labels: size/S

#739 Send policy wrappers
  api/aperture/plugins/fluxninja/v1/heartbeat.proto
  api/aperture/policy/wrappers/v1/policy.proto
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/policy_deepcopy.gen.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Labels: size/XL

#740 docs: regenerate api docs
  api/Makefile
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/policies/blueprints.md
  docs/content/references/api/agent/entity-cache-service-get-entity-by-ip-address.api.mdx
  docs/content/references/api/agent/entity-cache-service-get-entity-by-name.api.mdx
  docs/content/references/api/agent/entity-cache-service-get-entity-cache.api.mdx
  docs/content/references/api/agent/info-service-host.api.mdx
  docs/content/references/api/agent/info-service-process.api.mdx
  docs/content/references/api/agent/info-service-version.api.mdx
  docs/content/references/api/agent/peer-discovery-service-get-peer.api.mdx
  docs/content/references/api/agent/peer-discovery-service-get-peers.api.mdx
  docs/content/references/api/agent/status-service-get-group-status.api.mdx
  docs/content/references/api/controller/info-service-host.api.mdx
  docs/content/references/api/controller/info-service-process.api.mdx
  docs/content/references/api/controller/info-service-version.api.mdx
  docs/content/references/api/controller/policy-service-get-policies.api.mdx
  docs/content/references/api/controller/status-service-get-group-status.api.mdx
  go.mod
  go.sum
Labels: size/XXL

#742 precommit: update go-swagger
  .pre-commit-config.yaml
  go.mod
  go.sum
Labels: size/XS

#662 Bump Golang deps
  go.mod
  go.sum
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/enrichmentprocessor/processor.go
  pkg/otelcollector/enrichmentprocessor/processor_metrics_test.go
  pkg/otelcollector/helpers.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor_test.go
Labels: size/L

#729 Save signals metrics to status on tick
  api/aperture/policy/language/v1/signal_metrics.proto
  api/gen/proto/go/aperture/policy/language/v1/signal_metrics.pb.go
  api/gen/proto/go/aperture/policy/language/v1/signal_metrics.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/signal_metrics_deepcopy.gen.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/runtime/circuit.go
Labels: size/L

#744 Add .dockerignore and use caching in operator Dockerfile
  .circleci/config.yml
  .dockerignore
  operator/Dockerfile
  playground/Tiltfile
Labels: size/M

#746 tools: isolate tools.go to separate go.mod
  .pre-commit-config.yaml
  Makefile
  go.mod
  go.sum
  scripts/install_go_tools.sh
  tools/go/go.mod
  tools/go/go.sum
  tools/go/tools.go
Labels: size/S

#747 scheduler: default to non continuousTracking behavior for load shed t…
  pkg/policies/dataplane/actuators/concurrency/auto-tokens.go
  pkg/policies/dataplane/actuators/concurrency/load-shed-actuator.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket-load-shed.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq_test.go
Labels: size/M

#748 swagger: tweaks and remove generated api mdx files
  .circleci/continue-workflows.yml
  Makefile
  api/Makefile
  blueprints/Makefile
  blueprints/lib/README.md
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  docs/Makefile
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/concepts/flow-control/concurrency-limiter.md
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/flow-control/rate-limiter.md
  docs/content/concepts/flow-control/selector.md
  docs/content/concepts/policy/circuit.md
  docs/content/concepts/policy/policy.md
  docs/content/concepts/policy/resources.md
  docs/content/references/api/_category_.yml
  docs/content/references/api/agent/entity-cache-service-get-entity-by-ip-address.api.mdx
  docs/content/references/api/agent/entity-cache-service-get-entity-by-name.api.mdx
  docs/content/references/api/agent/entity-cache-service-get-entity-cache.api.mdx
  docs/content/references/api/agent/info-service-host.api.mdx
  docs/content/references/api/agent/info-service-process.api.mdx
  docs/content/references/api/agent/info-service-version.api.mdx
  docs/content/references/api/agent/peer-discovery-service-get-peer.api.mdx
  docs/content/references/api/agent/peer-discovery-service-get-peers.api.mdx
  docs/content/references/api/agent/status-service-get-group-status.api.mdx
  docs/content/references/api/controller/info-service-host.api.mdx
  docs/content/references/api/controller/info-service-process.api.mdx
  docs/content/references/api/controller/info-service-version.api.mdx
  docs/content/references/api/controller/policy-service-get-policies.api.mdx
  docs/content/references/api/controller/status-service-get-group-status.api.mdx
  docs/content/references/configuration/policy.md
  docs/gen/policy/config-swagger.yaml
  docs/gen/policy/metadata
  docs/gen/policy/policy.yaml
  operator/Dockerfile
Labels: size/XL

#716 Add signals grafana dashboard
  blueprints/blueprints/latency-gradient/example/gen/dashboards/example.json
  blueprints/lib/1.0/dashboards/dashboards.libsonnet
  blueprints/lib/1.0/dashboards/latency-gradient/latency-gradient.libsonnet
  blueprints/lib/1.0/dashboards/signals/signals.libsonnet
  blueprints/lib/1.0/grafana/aperture.libsonnet
  blueprints/lib/1.0/grafana/aperture/timeseries.libsonnet
  blueprints/lib/1.0/grafana/panels/timeseries_panel.libsonnet
  playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/L

#749 blueprints: add policy name filter to signals dashboard
  blueprints/blueprints/latency-gradient/README.md
  blueprints/blueprints/latency-gradient/config.libsonnet
  blueprints/blueprints/latency-gradient/example/example.jsonnet
  blueprints/blueprints/latency-gradient/example/gen/dashboards/example-signals.json
  blueprints/blueprints/latency-gradient/main.libsonnet
  blueprints/blueprints/latency-gradient/metadata.yaml
  blueprints/lib/1.0/dashboards/signals/signals.libsonnet
  blueprints/scripts/blueprint-readme-generator.py
  playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/L

#673 SDK Validation Harness
  cmd/sdk-validator/main.go
  cmd/sdk-validator/validator/flowcontrol.go
  cmd/sdk-validator/validator/provide.go
  cmd/sdk-validator/validator/trace.go
  go.mod
  playground/Tiltfile
  test/aperture_suite_test.go
  test/info_test.go
Labels: size/L

#753 Start checking for plugin build errors in Dockerfiles 🙃
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  playground/Tiltfile
Labels: size/S

#755 Stop watching code directly from Tiltfile
  playground/Tiltfile
Labels: size/XS

#665 JobMetrics for job framework
  pkg/distcache/provider.go
  pkg/jobs/basic-job.go
  pkg/jobs/http-job.go
  pkg/jobs/job-group.go
  pkg/jobs/job-metrics.go
  pkg/jobs/job.go
  pkg/jobs/jobs_test.go
  pkg/jobs/multi-job.go
  pkg/jobs/provide.go
  pkg/metrics/schema.go
  pkg/policies/controlplane/components/promql.go
  pkg/policies/controlplane/policy.go
  pkg/policies/dataplane/actuators/rate/ratetracker/lazy-sync-rate-tracker.go
  pkg/watchdog/watchdog.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Labels: size/L

#759 Revert distache metrics code (datarace)
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  pkg/distcache/distcache-metrics.go
  pkg/distcache/provider.go
  pkg/policies/controlplane/circuit-graph.go
Labels: size/XXL

#762 Revert "JobMetrics for job framework"
  pkg/jobs/basic-job.go
  pkg/jobs/http-job.go
  pkg/jobs/job-group.go
  pkg/jobs/job-metrics.go
  pkg/jobs/job.go
  pkg/jobs/jobs_test.go
  pkg/jobs/multi-job.go
  pkg/jobs/provide.go
  pkg/metrics/schema.go
  pkg/policies/controlplane/components/promql.go
  pkg/policies/controlplane/policy.go
  pkg/policies/dataplane/actuators/rate/ratetracker/lazy-sync-rate-tracker.go
  pkg/watchdog/watchdog.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Labels: size/L

#763 compiler: re-add signalname labels to dot graphs
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/rate-limiter/example/gen/graph/graph.svg
  pkg/policies/controlplane/circuit-graph.go
Labels: size/XL

#765 First valid
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/component.libsonnet
  blueprints/lib/1.0/_gen/v1/firstvalid.libsonnet
  blueprints/lib/1.0/_gen/v1/firstvalidins.libsonnet
  blueprints/lib/1.0/_gen/v1/firstvalidouts.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/component-factory.go
  pkg/policies/controlplane/components/first-valid.go
Labels: size/XXL

#770 Use UTC time in telemetry logs
  pkg/otelcollector/rollupprocessor/processor.go
Labels: size/XS

#772 Readd Distcache metrics
  pkg/distcache/distcache-metrics.go
  pkg/distcache/provider.go
Labels: size/L

#773 blueprints: unify LATENCY_OVERLOAD and LATENCY_SETPOINT
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.dot
  blueprints/blueprints/latency-gradient/example/gen/graph/graph.svg
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/components/ema.go
  pkg/status/registry.go
Labels: size/XXL

#774 platform: check nil when detaching registry
  pkg/status/registry.go
Labels: size/XS

#775 Refactor scalarResultBroker and taggedResultBroker
  blueprints/blueprints/latency-gradient/example/gen/dashboards/example-signals.json
  blueprints/lib/1.0/dashboards/signals/signals.libsonnet
  pkg/policies/controlplane/components/promql.go
  pkg/prometheus/prom-query.go
  pkg/prometheus/scalar-query.go
Labels: size/M

#777 Bump OTEL to 0.62.1
  cmd/aperture-agent/agent/otel-component.go
  go.mod
  go.sum
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/enrichmentprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor.go
Labels: size/S

#779 Cap request timeout in scheduler by grpc client timeout
  pkg/flowcontrol/common/flowcontrol.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq_test.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/limiter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_limiter.go
Labels: size/L

#780 scheduler: adjust client deadline and fix metric gauges
  api/aperture/policy/language/v1/policy.proto
  api/buf.lock
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq.go
Labels: size/M

#783 Scheduler: Load Multiplier
  api/aperture/policy/decisions/v1/decisions.proto
  api/aperture/policy/language/v1/policy.proto
  api/aperture/policy/wrappers/v1/decisions.proto
  api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.go
  api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/decisions/v1/decisions_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions.pb.json.go
  api/gen/proto/go/aperture/policy/wrappers/v1/decisions_deepcopy.gen.go
  blueprints/blueprints/latency-gradient/example/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/concurrencylimiter.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/loadactuator.libsonnet
  blueprints/lib/1.0/_gen/v1/loadactuatorins.libsonnet
  blueprints/lib/1.0/_gen/v1/loadshedactuator.libsonnet
  blueprints/lib/1.0/_gen/v1/loadshedactuatorins.libsonnet
  blueprints/lib/1.0/policies/latency-gradient/latency-gradient.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/concepts/policy/circuit.md
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/metrics/schema.go
  pkg/otelcollector/config.go
  pkg/policies/common/paths.go
  pkg/policies/controlplane/component-stack-factory.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/actuators/concurrency/load-shed-actuator.go
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
  pkg/policies/controlplane/components/promql.go
  pkg/policies/controlplane/validator_test.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/concurrency/load-actuator.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket-load-multiplier.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/wfq_test.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XXL

#785 Run jb install also in generate-doc-assets hook
  docs/tools/jsonnet/generate_jsonnet.sh
Labels: size/XS

#782 rollupprocessor: Apply per-batch attribute cardinality limit
  cmd/aperture-agent/agent/otel-component.go
  docs/content/concepts/flow-control/flow-label.md
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor_test.go
Labels: size/L

#787 Add jobs for building aperture-java
  .circleci/config.yml
  .circleci/continue-workflows.yml
  .pre-commit-config.yaml
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/App.java
Labels: size/L

#792 Add send_batch_max_size option
  cmd/aperture-agent/agent/otel-component.go
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent/config_test.tpl
  operator/controllers/agent/configmaps_test.go
  operator/controllers/controller/config_test.tpl
  operator/controllers/controller/configmaps_test.go
  pkg/otelcollector/config.go
  pkg/otelcollector/zz_generated.deepcopy.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/L

#793 v0.6.1 release
  cmd/aperture-agent/agent/otel-component.go
  docs/content/concepts/flow-control/flow-label.md
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent/config_test.tpl
  operator/controllers/agent/configmaps_test.go
  operator/controllers/controller/config_test.tpl
  operator/controllers/controller/configmaps_test.go
  pkg/otelcollector/config.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor_test.go
  pkg/otelcollector/zz_generated.deepcopy.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/L

#796 blueprints: tweak defaults and rename config params and docs
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/examples/rate-limiter/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/README.md
  blueprints/lib/1.0/blueprints/rate-limiter/config.libsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
Labels: size/XXL

#790 Java SDK: Accept flow in case of unresponsive agent
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
Labels: size/S

#804 api: fix generator on macOS
  api/Makefile
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.go
  api/gen/proto/go/aperture/common/info/v1/info.pb.go
  api/gen/proto/go/aperture/common/peers/v1/peers.pb.go
  api/gen/proto/go/aperture/common/status/v1/status.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/CheckRequest.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/CheckRequestOrBuilder.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/CheckResponse.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/CheckResponseOrBuilder.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/ClassifierInfo.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/ClassifierInfoOrBuilder.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/ControlPointInfo.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/ControlPointInfoOrBuilder.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/FlowControlServiceGrpc.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/FlowcontrolProto.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/FluxMeterInfo.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/FluxMeterInfoOrBuilder.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/LimiterDecision.java
  api/gen/proto/java/com/fluxninja/aperture/flowcontrol/v1/LimiterDecisionOrBuilder.java
Labels: size/XXL

#803 Extrapolation before Load Multiplier input
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
Labels: size/XXL

#801 Docs: Typo and elaborate more about scheduler output signals
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
Labels: size/S

#808 docs: basic concurrency limiting tutorial
  blueprints/README.md
  docs/content/concepts/policy/policy.md
  docs/content/get-started/installation/agent/supported-platforms.md
  docs/content/get-started/installation/controller.md
  docs/content/get-started/policies/_category_.yml
  docs/content/get-started/policies/assets/monitoring/signals-dashboard.json
  docs/content/get-started/policies/assets/monitoring/signals-dashboard.jsonnet
  docs/content/get-started/policies/blueprints.md
  docs/content/get-started/policies/monitoring.md
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.md5sum
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.png
  docs/content/policies/assets/gen/blueprints/jsonnet/blueprints_0.mmd.svg
  docs/content/policies/tutorial/tutorial.md
  docs/content/tutorials/_category_.yml
  docs/content/tutorials/flow-control/_category_.yml
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.yaml
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/static-rate-limiting.md
  docs/content/tutorials/signal-processing/_category_.yml
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.jsonnet
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.md5sum
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.png
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.svg
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.yaml
  docs/content/tutorials/signal-processing/assets/detecting-overload/is_overload_switch.png
  docs/content/tutorials/signal-processing/assets/detecting-overload/latency.png
  docs/content/tutorials/signal-processing/assets/detecting-overload/latency_ema.png
  docs/content/tutorials/signal-processing/assets/detecting-overload/latency_setpoint.png
  docs/content/tutorials/signal-processing/detecting-overload.md
  playground/load_generator/scenarios/load_test.js
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XL

#810 playground: revert scenario changes
  playground/load_generator/scenarios/load_test.js
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/L

#809 K8s discovery
  pkg/discovery/kubernetes/kubernetes_discovery.go
  pkg/notifiers/notifier_test.go
Labels: size/L

#813 docs: annotate grafana dashboard image
  docs/content/assets/img/grafana_dashboard.png
Labels: size/XS

#818 Fix nil pointer error in runDockerContainer
  cmd/sdk-validator/main.go
Labels: size/XS

#819 docs: playground doc updates
  .circleci/config.yml
  .circleci/continue-workflows.yml
  .tool-versions
  README.md
  api/aperture/common/entitycache/v1/entitycache.proto
  api/aperture/common/info/v1/info.proto
  api/aperture/common/labelmatcher/v1/labelmatcher.proto
  api/aperture/common/peers/v1/peers.proto
  api/aperture/common/selector/v1/selector.proto
  api/aperture/common/status/v1/status.proto
  api/aperture/plugins/fluxninja/v1/heartbeat.proto
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/language/v1/policy.proto
  api/buf.lock
  docs/content/assets/gen/introduction/architecture_simple.mmd
  docs/content/assets/gen/introduction/architecture_simple.mmd.md5sum
  docs/content/assets/gen/introduction/architecture_simple.mmd.png
  docs/content/assets/gen/introduction/architecture_simple.mmd.svg
  docs/content/get-started/assets/playground/playground-app.mmd
  docs/content/get-started/assets/playground/playground-app.mmd.md5sum
  docs/content/get-started/assets/playground/playground-app.mmd.png
  docs/content/get-started/assets/playground/playground-app.mmd.svg
  docs/content/get-started/playground.md
  docs/content/introduction.md
  go.mod
  playground/Tiltfile
  playground/browser/go.mod
  playground/browser/go.sum
  playground/browser/main.go
  playground/demo_app/Dockerfile
  playground/demo_app/README.md
  playground/demo_app/app/app.go
  playground/demo_app/app/app_test.go
  playground/demo_app/go.mod
  playground/demo_app/go.sum
  playground/demo_app/main.go
  playground/tanka/chartfile.yaml
Labels: size/XL

#821 Rollup based on metrics
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor_test.go
  pkg/otelcollector/rollupprocessor/rollup.go
Labels: size/M

#822 docs: FluxMeter --> Flux Meter
  api/aperture/common/selector/v1/selector.proto
  api/aperture/policy/language/v1/fluxmeter.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/common/selector/v1/selector.pb.go
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/diagrams/architecture/aperture.mmd
  docs/content/assets/diagrams/architecture/aperture.mmd.md5sum
  docs/content/assets/diagrams/architecture/aperture.mmd.png
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/concepts/flow-control/flux-meter.md
  docs/content/concepts/policy/resources.md
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/policy.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/policy/policy.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  pkg/agentinfo/agent-info.go
Labels: size/L

#823 playground: minor tweaks in Tiltfile
  playground/Tiltfile
Labels: size/XS

#824 Fix tutorials and demo_app
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
  playground/demo_app/main.go
Labels: size/S

#825 platform: panic handler minor fix
  pkg/panichandler/panichandler.go
  playground/tanka/apps/aperture-agent/mixins.libsonnet
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XS

#826 Dry run mode for Load Actuator
  api/aperture/policy/decisions/v1/decisions.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/decisions/v1/decisions.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/examples/rate-limiter/gen/graph/graph.svg
  blueprints/examples/rate-limiter/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/gradientcontroller.libsonnet
  blueprints/lib/1.0/_gen/v1/loadactuator.libsonnet
  blueprints/lib/1.0/_gen/v1/loadactuatordynamicconfig.libsonnet
  blueprints/lib/1.0/_gen/v1/ratelimiter.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/policy.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/common/paths.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/actuators/rate/rate-limiter.go
  pkg/policies/controlplane/components/controller/controller-component.go
  pkg/policies/controlplane/components/controller/gradient.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/concurrency/load-actuator.go
  pkg/policies/dataplane/actuators/concurrency/scheduler/token-bucket-load-multiplier.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
Labels: size/XXL

#830 docs: dynamic configuration
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/get-started/policies/blueprints.md
  docs/content/get-started/policies/dynamic-configuration.md
  docs/content/get-started/policies/monitoring.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
Labels: size/XL

#833 docs: add a note regarding dryrun mode
  docs/content/concepts/flow-control/rate-limiter.md
  docs/content/get-started/policies/blueprints.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.jsonnet
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/static-rate-limiting.md
Labels: size/M

#828 Response status in telemetry
  pkg/otelcollector/consts.go
  pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
  pkg/otelcollector/metricsprocessor/internal/check_response_labels_test.go
  pkg/otelcollector/metricsprocessor/internal/envoy_labels.go
  pkg/otelcollector/metricsprocessor/internal/envoy_labels_test.go
  pkg/otelcollector/metricsprocessor/internal/internal_suite_test.go
  pkg/otelcollector/metricsprocessor/internal/labels_filter.go
  pkg/otelcollector/metricsprocessor/internal/sdk_labels.go
  pkg/otelcollector/metricsprocessor/internal/sdk_labels_test.go
  pkg/otelcollector/metricsprocessor/internal/status.go
  pkg/otelcollector/metricsprocessor/internal/status_test.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/flux-meter.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_flux_meter.go
Labels: size/XXL

#834 Bump OTEL to 0.63.0
  go.mod
  go.sum
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/otelcollector/otelcollector.go
  pkg/otelcollector/rollupprocessor/processor.go
Labels: size/S

#812 Move java SDK release job to a workload triggered on semver tags
  .circleci/config.yml
  .circleci/post-release.yaml
Labels: size/M

#835 Fix telemetry labels propagation
  pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
  pkg/otelcollector/metricsprocessor/internal/check_response_labels_test.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
Labels: size/M

#837 Fix Load Multiplier Panel
  blueprints/examples/latency-gradient/gen/dashboards/example.json
  blueprints/lib/1.0/blueprints/latency-gradient/dashboard.libsonnet
Labels: size/XS

#836 TickInfo in LoadDecision
  api/aperture/policy/sync/v1/concurrency_limiter.proto
  api/aperture/policy/sync/v1/tick.proto
  api/gen/proto/go/aperture/policy/sync/v1/concurrency_limiter.pb.go
  api/gen/proto/go/aperture/policy/sync/v1/tick.pb.go
  api/gen/proto/go/aperture/policy/sync/v1/tick.pb.json.go
  api/gen/proto/go/aperture/policy/sync/v1/tick_deepcopy.gen.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/runtime/tick-info.go
Labels: size/L

#838 charts: bump prometheus and etcd
  manifests/charts/aperture-agent/Chart.lock
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.lock
  manifests/charts/aperture-controller/Chart.yaml
Labels: size/S

#839 Ignore negative workload latency
  pkg/otelcollector/metricsprocessor/internal/envoy_labels.go
  pkg/otelcollector/metricsprocessor/processor.go
Labels: size/M

#840 Skip NaN auto-tokens
  pkg/policies/controlplane/components/actuators/concurrency/scheduler.go
Labels: size/S

#769 Switched to SSH instead of HTTP for GitHub operations
  .circleci/scripts/helm_release.sh
Labels: size/XS

#663 add circleci pre-commit v2
  .circleci/continue-workflows.yml
  .pre-commit-config.yaml
  .tool-versions
  scripts/manage_tools.sh
Labels: size/S

#843 Revamp workload and flux meter metrics and labels
  blueprints/examples/latency-gradient/gen/dashboards/example.json
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/dashboard.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/metrics/schema.go
  pkg/otelcollector/consts.go
  pkg/otelcollector/helpers.go
  pkg/otelcollector/metricsprocessor/internal/envoy_labels.go
  pkg/otelcollector/metricsprocessor/internal/labels_filter.go
  pkg/otelcollector/metricsprocessor/internal/sdk_labels.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/rollup.go
  pkg/policies/dataplane/actuators/concurrency/concurrency-limiter.go
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/classifier.go
  pkg/policies/dataplane/iface/limiter.go
  pkg/policies/dataplane/resources/classifier/classifier.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_classifier.go
  pkg/policies/mocks/mock_limiter.go
Labels: size/XXL

#845 circleci pre-commit version change
  .pre-commit-config.yaml
Labels: size/XS

#846 Added R/W keys for Helm chart release
  .circleci/config.yml
Labels: size/XS

#847 Added ssh key usage for helm release
  .circleci/config.yml
Labels: size/XS

#848 Changes from main to stable/0.8.x for rc.4
  .circleci/config.yml
Labels: size/XS

#849 Downgrade bitnami/common to 1.17.1
  manifests/charts/aperture-agent/Chart.lock
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.lock
  manifests/charts/aperture-controller/Chart.yaml
Labels: size/S

#852 Added missing flag in the controller installation steps
  docs/content/get-started/installation/controller.md
Labels: size/XS
