Repository fluxninja/aperture, pull requests merged in 2022-08, with the labels that each got.

#181 Update code for aperture-mixin repo rename
  .circleci/continue-workflows.yml
  manifests/k8s/tanka/jsonnetfile.json
  manifests/k8s/tanka/jsonnetfile.lock.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/S

#184 Bump OTEL to 0.58.0
  go.mod
  go.sum
  pkg/otelcollector/config.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/loggingexporter/factory.go
  pkg/otelcollector/loggingexporter/logging_exporter.go
  pkg/otelcollector/loggingexporter/logging_exporter_test.go
  pkg/otelcollector/metricsprocessor/factory.go
Labels: size/M

#179 Extract policy compiler
  cmd/aperture-controller/controller/provider.go
  pkg/policies/controlplane/circuit-factory.go
  pkg/policies/controlplane/component-factory.go
  pkg/policies/controlplane/component-stack-factory.go
  pkg/policies/controlplane/policy-factory.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/runtime/circuit.go
Labels: size/L

#162 Status code labels in FluxMeter
  pkg/metrics/schema.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/fluxmeter/flux-meter.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/flux-meter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_flux_meter.go
Labels: size/L

#191 Some fixes to aperture grafana deployment
  manifests/k8s/tanka/jsonnetfile.json
  manifests/k8s/tanka/jsonnetfile.lock.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/M

#192 Replace all instances of agent-prometheus with aperture-prometheus
  manifests/k8s/Tiltfile
  manifests/k8s/tanka/environments/tilt/apps/aperture-grafana/dashboards/json-example.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
  operator/controllers/configmaps_test.go
  operator/controllers/controller_config_with_fluxninja_plugin_test.tpl
  operator/controllers/controller_config_without_fluxninja_plugin_test.tpl
Labels: size/S

#160 Expand doc comments for policies
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/gen/policies/swagger.md
Labels: size/XL

#195 Remove sidebar.json
  docs/content/sidebars.json
Labels: size/XS

#199 Lowercase dirnames in docs and other tweaks
  docs/content/concepts/_category_.yml
  docs/content/concepts/actuators/actuators.md
  docs/content/concepts/actuators/scheduler.md
  docs/content/concepts/flow-control.md
  docs/content/developers/_category_.yml
  docs/content/developers/cla.md
  docs/content/faq.md
  docs/content/introduction.md
  docs/content/reference/_category_.yml
  docs/content/reference/configuration/_category_.yml
Labels: size/M

#201 Flow is not flow control
  docs/content/concepts/flow.md
Labels: size/XS

#200 Fix Controller OTEL pipelines
  pkg/otel/components.go
  pkg/otel/config.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/S

#204 Fix markdown glitches in generated classifiers documentation
  api/aperture/classification/v1/extractor.proto
  api/aperture/classification/v1/ruleset.proto
  api/aperture/common/labelmatcher/v1/labelmatcher.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/classification/v1/extractor.pb.go
  api/gen/proto/go/aperture/classification/v1/ruleset.pb.go
  api/gen/proto/go/aperture/common/labelmatcher/v1/labelmatcher.pb.go
  docs/gen/classification/swagger.md
  docs/gen/policies/swagger.md
Labels: size/L

#207 add sidebars.json
  docs/content/sidebars.json
Labels: size/XS

#208 Faq
  docs/content/faq.md
  docs/content/feedback.md
  docs/content/introduction.md
  docs/content/setup.md
Labels: size/M, C-Documentation

#205 Policy Blueprints Documentation
  docs/content/concepts/policies/policy-blueprints.md
Labels: size/L

#210 Start flow control section
  docs/content/concepts/flow-control/actuators/actuators.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/selector.md
  docs/content/concepts/flow.md
  docs/content/concepts/policies/policies.md
  docs/content/faq.md
  docs/content/sidebars.json
Labels: size/L

#212 Add metrics names to common schema
  pkg/flowcontrol/metrics.go
  pkg/jobs/job-metrics.go
  pkg/metrics/schema.go
  pkg/policies/dataplane/actuator/concurrency/load-shed-actuator.go
  pkg/policies/dataplane/actuator/concurrency/scheduler/wfq_test.go
Labels: size/M

#214 Move around some files
  .circleci/continue-workflows.yml
  .circleci/scripts/asdf_install.sh
  .pre-commit-config.yaml
  Makefile
  manifests/k8s/Tiltfile
  pkg/tools/tools.go
  scripts/install_go_tools.sh
  scripts/manage_tools.sh
  scripts/precommit/check_tanka_show.sh
  scripts/precommit/generate_api.sh
  scripts/precommit/generate_docs.sh
  tools/demo_app/README.md
  tools/demo_app/app/app.go
  tools/demo_app/cmd/demo_app/main.go
  tools/demo_app/tools/tools.go
  tools/githooks/install_go_tools.sh
  tools/load_generator/scenarios/demoapp-stress-test-cr.yaml
  tools/load_generator/scenarios/stress_test.js
Labels: size/L

#216 precommit fix
  .pre-commit-config.yaml
  manifests/k8s/tanka/jsonnetfile.lock.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/M

#217 improve python tools install
  .github/dependabot.yml
  .pre-commit-config.yaml
  Makefile
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
  libsonnet/1.0/_gen/v1/gen.libsonnet
  libsonnet/1.0/_gen/v1/languagev1ratelimiter.libsonnet
  libsonnet/1.0/_gen/v1/ratelimiterlazysync.libsonnet
  libsonnet/1.0/_gen/v1/ratelimiteroverride.libsonnet
  pkg/policies/dataplane/actuators/rate/rate-limiter.go
  requirements.txt
  scripts/manage_tools.sh
  scripts/precommit/generate_docs.sh
  scripts/precommit/generate_libsonnet.sh
Labels: size/XL

#234 Fix tools install
  scripts/manage_tools.sh
Labels: size/S

#194 Expose k8s client HTTP client config
  cmd/aperture-agent/agent.go
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  pkg/k8s/provide.go
Labels: size/M

#238 Fixed DockerHub latest tag issue
  .circleci/continue-workflows.yml
Labels: size/XS

#242 combine pip PRs
  .github/workflows/combine-prs.yml
Labels: size/S

#244 Fix combine PRs script
  .github/workflows/combine-prs.yml
Labels: size/S

#248 Improve blueprint docs
  docs/content/concepts/policies/policy-blueprints.md
Labels: size/XS

#235 Enhance Policy Compiler for Circuit Graph creation
  pkg/policies/controlplane/circuit-factory.go
  pkg/policies/controlplane/component-factory.go
  pkg/policies/controlplane/component-stack-factory.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/runtime/circuit.go
Labels: size/L

#241 De-couple FluxMeters from Policy, make them global
  api/aperture/common/config/v1/config_properties_wrapper.proto
  api/aperture/flowcontrol/v1/flowcontrol.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/config/v1/config_properties_wrapper.pb.go
  api/gen/proto/go/aperture/flowcontrol/v1/flowcontrol.pb.go
  libsonnet/Makefile
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/paths/paths.go
  pkg/policies/controlplane/resources/fluxmeter/flux-meter.go
  pkg/policies/dataplane/engine.go
  pkg/policies/dataplane/engine_test.go
  pkg/policies/dataplane/iface/engine.go
  pkg/policies/dataplane/iface/flux-meter.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
  pkg/policies/mocks/mock_engine.go
  pkg/policies/mocks/mock_flux_meter.go
Labels: size/L

#159 Expose batch configuration
  manifests/charts/agent/files/aperture-agent-config.yaml
  manifests/charts/agent/values.yaml
  operator/api/v1alpha1/agent_types.go
  operator/api/v1alpha1/common_types.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/controllers/configmaps_test.go
  pkg/otel/config.go
Labels: size/M

#250 Add comment why histogram might already exists in metricsprocessor
  pkg/otelcollector/metricsprocessor/processor.go
Labels: size/XS

#239 Updated K6 CRD
  manifests/k8s/tanka/lib/apps/k6-operator/k6/crd/bases/k6.io_k6s.yaml
Labels: size/M

#249 Removed Istio dependency from chart and added policy configmap and grafana dashboard
  Makefile
  manifests/charts/agent/Chart.lock
  manifests/charts/agent/Chart.yaml
  manifests/charts/agent/README.md
  manifests/charts/agent/templates/envoy_filter.yaml
  manifests/charts/agent/values.yaml
  manifests/charts/aperture-operator/Chart.lock
  manifests/charts/aperture-operator/Chart.yaml
  manifests/charts/aperture-operator/README.md
  manifests/charts/aperture-operator/values.yaml
  manifests/charts/istioconfig/.helmignore
  manifests/charts/istioconfig/Chart.yaml
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  manifests/charts/istioconfig/values.yaml
  manifests/k8s/Tiltfile
  manifests/k8s/tanka/chartfile.yaml
  manifests/k8s/tanka/charts/.gitignore
  manifests/k8s/tanka/charts/istioconfig
  manifests/k8s/tanka/environments/tilt/apps/aperture-grafana/dashboards/json-example.json
  manifests/k8s/tanka/environments/tilt/apps/aperture-operator/mixins.libsonnet
  manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet
  manifests/k8s/tanka/environments/tilt/apps/istio/main.jsonnet
  manifests/k8s/tanka/environments/tilt/apps/istio/mixins.libsonnet
  manifests/k8s/tanka/jsonnetfile.lock.json
  manifests/k8s/tanka/lib/apps/aperture-grafana/main.libsonnet
  manifests/k8s/tanka/lib/apps/istio/main.libsonnet
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent_reconciler.go
  operator/controllers/controller_reconciler.go
Labels: size/XL

#251 Fix CLA rendering and improve aperture-operator handling
  docs/content/developers/cla.md
  manifests/charts/aperture-operator/templates/_helpers.tpl
  manifests/charts/aperture-operator/values.yaml
  manifests/k8s/README.md
  manifests/k8s/Tiltfile
Labels: size/M

#253 add app and helm chart version
  manifests/charts/agent/Chart.yaml
  manifests/charts/aperture-operator/Chart.yaml
Labels: size/XS

#237 Added installation steps in docs
  .gitignore
  docs/content/setup/_category_.yml
  docs/content/setup/installation/_category_.yml
  docs/content/setup/installation/agent/_category_.yml
  docs/content/setup/installation/agent/agent.md
  docs/content/setup/installation/agent/daemonset.md
  docs/content/setup/installation/agent/sidecar.md
  docs/content/setup/installation/controller.md
  docs/content/setup/installation/installation.md
  docs/content/setup/istio.md
  docs/content/setup/supported-platforms.md
Labels: size/XL

#246 Content
  docs/content/concepts/flow-control/actuators/actuators.md
  docs/content/concepts/flow-control/actuators/rate-limiter.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/content/concepts/flow-control/selector.md
Labels: size/M, C-Documentation

#252 Add FluxNinja Cloud section to docs
  docs/content/cloud/_category_.yml
  docs/content/cloud/plugin.md
Labels: size/M

#240 Single demoapp depoyment per worker node
  manifests/charts/demo-app/templates/deployment.yaml
  manifests/k8s/Tiltfile
  manifests/k8s/tanka/environments/tilt/apps/demoapp/mixins.libsonnet
Labels: size/S

#258 Added null checks for values in chart
  manifests/charts/aperture-operator/templates/_helpers.tpl
  manifests/charts/aperture-operator/templates/agent.yaml
  manifests/charts/aperture-operator/templates/controller.yaml
  manifests/charts/aperture-operator/templates/pre-delete-hook.yaml
Labels: size/L

#259 Add Kind cluster configuration file
  manifests/k8s/README.md
  manifests/k8s/kind-config.yaml
Labels: size/S

#260 Remove batchMetricsFast processor
  manifests/charts/agent/files/aperture-agent-config.yaml
  manifests/charts/agent/values.yaml
  manifests/charts/aperture-operator/README.md
  manifests/charts/aperture-operator/templates/agent.yaml
  manifests/charts/aperture-operator/values.yaml
  operator/api/v1alpha1/agent_types.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/controllers/agent_config.tpl
  operator/controllers/agent_config_with_fluxninja_plugin_test.tpl
  operator/controllers/configmaps.go
  operator/controllers/configmaps_test.go
  pkg/otel/config.go
Labels: size/M

#269 rename entity cache messages
  api/aperture/common/entitycache/v1/entitycache.proto
  api/aperture/plugins/fluxninja/v1/heartbeat.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.gw.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache.pb.json.go
  api/gen/proto/go/aperture/common/entitycache/v1/entitycache_grpc.pb.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.go
  cmd/aperture-agent/Dockerfile
  cmd/aperture-agent/agent.go
  cmd/aperture-controller/Dockerfile
  docs/gen/policies/gen.yaml
  manifests/charts/agent/files/aperture-agent-config.yaml
  pkg/entitycache/entity_cache.go
  pkg/platform/platform.go
  pkg/status/provide.go
  pkg/status/status-service.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
Labels: size/XL

#270 Update aperture-agent-config.yaml
  manifests/charts/agent/files/aperture-agent-config.yaml
Labels: size/XS

#263 Expand rate limiter docs + misc doc tweaks
  api/aperture/policy/language/v1/classifier.proto
  api/aperture/policy/language/v1/policy.proto
  api/gen/openapiv2/aperture.swagger.yaml
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/cloud/plugin.md
  docs/content/concepts/flow-control/actuators/rate-limiter.md
  docs/content/concepts/flow-control/actuators/scheduler.md
  docs/gen/policies/gen.yaml
  docs/gen/policies/policy.md
Labels: size/XXL

#272 pprof tweaks
  docs/gen/config/aperture-agent/config-swagger.yaml
  docs/gen/config/aperture-agent/swagger.md
  docs/gen/config/aperture-controller/config-swagger.yaml
  docs/gen/config/aperture-controller/swagger.md
  pkg/net/http/server.go
  pkg/profilers/profilers.go
Labels: size/M

#273 Make demoapp latency configurable
  tools/demo_app/README.md
  tools/demo_app/app/app.go
  tools/demo_app/cmd/demo_app/main.go
Labels: size/S
