Repository fluxninja/aperture, pull requests merged in 2022-12, with the labels that each got.

#937 demoapp: Improve visibility of sampled logs
  playground/demo_app/app/app.go
  playground/demo_app/go.mod
  playground/demo_app/go.sum
Labels: size/M

#980 Added details and support for smooth upgrade of aperture
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  manifests/charts/aperture-agent/README.md
  manifests/charts/aperture-agent/templates/_helpers.tpl
  manifests/charts/aperture-agent/templates/agent.yaml
  manifests/charts/aperture-agent/templates/deployment.yaml
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/templates/_helpers.tpl
  manifests/charts/aperture-controller/templates/controller.yaml
  manifests/charts/aperture-controller/templates/deployment.yaml
  manifests/charts/aperture-controller/values.yaml
  operator/controllers/agent/reconciler.go
  operator/controllers/controller/reconciler.go
Labels: size/L

#979 keep the policy name consistent throughout the docs
  docs/content/get-started/playground.md
  docs/content/get-started/policies/dynamic-configuration.md
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
Labels: size/S

#994 Prepare for release v0.13.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#991 Warn on unknown entity (take two)
  cmd/aperture-agent/agent.go
  cmd/sdk-validator/main.go
  pkg/discovery/kubernetes/kubernetes_discovery.go
  pkg/discovery/kubernetes/provide.go
  pkg/discovery/static/provide.go
  pkg/discovery/static/static_discovery.go
  pkg/discovery/static/static_discovery_test.go
  pkg/entitycache/entity_cache.go
  pkg/mocks/mock-trackers.go
  pkg/notifiers/tracker.go
  pkg/policies/flowcontrol/provide.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/check/check_test.go
  pkg/policies/flowcontrol/service/check/provide.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  pkg/policies/flowcontrol/service/envoy/authz_test.go
  pkg/policies/flowcontrol/service/provide.go
  pkg/policies/flowcontrol/servicegetter/servicegetter.go
  test/aperture_suite_test.go
Labels: size/L

#997 Add metrics for IP-to-services lookups
  pkg/metrics/schema.go
  pkg/policies/flowcontrol/provide.go
  pkg/policies/flowcontrol/servicegetter/metrics.go
  pkg/policies/flowcontrol/servicegetter/provide.go
  pkg/policies/flowcontrol/servicegetter/servicegetter.go
Labels: size/L

#998 Cherry-picked changes for release 0.13.0-rc.2
  cmd/aperture-agent/agent.go
  cmd/sdk-validator/main.go
  pkg/discovery/kubernetes/kubernetes_discovery.go
  pkg/discovery/kubernetes/provide.go
  pkg/discovery/static/provide.go
  pkg/discovery/static/static_discovery.go
  pkg/discovery/static/static_discovery_test.go
  pkg/entitycache/entity_cache.go
  pkg/metrics/schema.go
  pkg/mocks/mock-trackers.go
  pkg/notifiers/tracker.go
  pkg/policies/flowcontrol/provide.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/check/check_test.go
  pkg/policies/flowcontrol/service/check/provide.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  pkg/policies/flowcontrol/service/envoy/authz_test.go
  pkg/policies/flowcontrol/service/provide.go
  pkg/policies/flowcontrol/servicegetter/metrics.go
  pkg/policies/flowcontrol/servicegetter/provide.go
  pkg/policies/flowcontrol/servicegetter/servicegetter.go
  test/aperture_suite_test.go
Labels: size/L

#996 SDK tomcat support
  sdks/aperture-java/Dockerfile
  sdks/aperture-java/examples/armeria-example/src/main/java/com/fluxninja/example/ArmeriaServer.java
  sdks/aperture-java/examples/tomcat-example/build.gradle.kts
  sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/filter/ApertureFilter.java
  sdks/aperture-java/examples/tomcat-example/src/main/java/com/fluxninja/example/servlet/ApertureServlet.java
  sdks/aperture-java/examples/tomcat-example/src/main/webapp/WEB-INF/web.xml
  sdks/aperture-java/lib/tomcat7/build.gradle.kts
  sdks/aperture-java/lib/tomcat7/src/main/java/com/fluxninja/aperture/tomcat7/ApertureFilter.java
  sdks/aperture-java/lib/tomcat7/src/main/java/com/fluxninja/aperture/tomcat7/ServletUtils.java
  sdks/aperture-java/settings.gradle.kts
Labels: size/L

#1000 Make logs less noisy
  pkg/distcache/logwriter.go
  pkg/log/samplers.go
Labels: size/XS

#1001 Bump Aperture Java SDK to 0.13.0
  sdks/aperture-java/lib/core/src/main/java/com/fluxninja/aperture/sdk/Constants.java
  sdks/aperture-java/version.gradle.kts
Labels: size/XS

#1003 Update Java SDK badge
  sdks/aperture-java/README.md
Labels: size/XS

#1004 Remove alertmanagers test config
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/S

#993 Load actuator alerter
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/lib/1.0/_gen/v1/alerter.libsonnet
  blueprints/lib/1.0/_gen/v1/alerterconfig.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/loadactuator.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/policies/controlplane/component-factory_test.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/alerter.go
Labels: size/L

#992 Garbage collector in ETCD
  manifests/charts/aperture-controller/values.yaml
Labels: size/XS

#1007 Mark alert logs in otel with resource attribute
  pkg/alerts/alert.go
  pkg/otelcollector/alertsreceiver/receiver.go
  pkg/otelcollector/consts.go
Labels: size/XS

#1008 Fix alert tests
  pkg/alerts/alert_test.go
Labels: size/XS

#1006 Add default configuration for Load Actuator Alerter
  api/aperture/policy/language/v1/policy.proto
  api/buf.lock
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
Labels: size/M

#1009 Add GeneratorURL methods to alert
  pkg/alerts/alert.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/alerter.go
Labels: size/S

#1010 Changes for release v0.14.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1011 Added images which were directly committed to aperture-tech-docs
  docs/content/assets/img/adaptive-concurrency-limits/Signals-Dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/When-Aperture-is-protecting-service.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-light.png
  docs/content/assets/img/adaptive-concurrency-limits/demo-application.png
  docs/content/assets/img/adaptive-concurrency-limits/no-protection-setup.png
  docs/content/assets/img/adaptive-concurrency-limits/overall-view-grafana-dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-light.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-light.png
Labels: size/XS

#1015 Alerts improvements
  pkg/alertmanager/client/client.go
  pkg/alerts/alert.go
  pkg/otelcollector/alertsexporter/exporter.go
Labels: size/M

#1018 Add channel and severity helpers to alerts
  pkg/alerts/alert.go
  pkg/alerts/alert_test.go
  pkg/otelcollector/consts.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/alerter.go
Labels: size/L

#1016 Make alertmanager base path configurable
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/alertmanager/client/client.go
Labels: size/S

#1021 Fix parameter type in latency gradient blueprints doc
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
Labels: size/XS

#1020 jobs: publish liveness error on timeout
  api/aperture/status/v1/status.proto
  api/gen/proto/go/aperture/status/v1/status.pb.go
  api/gen/proto/go/aperture/status/v1/status.pb.json.go
  api/gen/proto/go/aperture/status/v1/status_deepcopy.gen.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  pkg/jobs/job.go
  pkg/jobs/jobs_test.go
  pkg/status/registry.go
  pkg/status/status-service.go
  pkg/status/status.go
Labels: size/L

#1017 refactor: Split circuit compilation and misc refactors
  cmd/circuit-compiler/main.go
  pkg/mapstruct/mapstruct.go
  pkg/policies/controlplane/circuitcompiler/compiler.go
  pkg/policies/controlplane/circuitfactory/circuitfactory_suite_test.go
  pkg/policies/controlplane/circuitfactory/compile.go
  pkg/policies/controlplane/circuitfactory/component-factory.go
  pkg/policies/controlplane/circuitfactory/component-factory_test.go
  pkg/policies/controlplane/circuitfactory/component-stack-factory.go
  pkg/policies/controlplane/circuitfactory/graph.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/controlplane/runtime/compile.go
  pkg/policies/controlplane/runtime/component.go
  pkg/policies/controlplane/runtime/ports.go
  pkg/policies/controlplane/validator.go
Labels: size/XXL

#1019 Add basic unit-test framework for testing circuits
  pkg/policies/controlplane/components/constant.go
  pkg/policies/controlplane/policy.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/controlplane/runtime/circuit_test.go
  pkg/policies/controlplane/sim/circuit.go
  pkg/policies/controlplane/sim/circuit_test.go
  pkg/policies/controlplane/sim/components.go
  pkg/policies/controlplane/sim/helpers.go
  pkg/policies/controlplane/sim/sim_suite_test.go
Labels: size/XL

#1027 Improve OLAP telemetry rollup
  cmd/aperture-agent/agent/otel-component.go
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  pkg/metrics/schema.go
  pkg/otelcollector/config.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor_test.go
  pkg/otelcollector/rollupprocessor/rollupprocessor_suite_test.go
  pkg/policies/flowcontrol/engine.go
Labels: size/M

#1029 refactor: Clean up rollup types initialization
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/rollupprocessor/rollup.go
Labels: size/L

#1026 Alerting tweaks
  api/aperture/policy/language/v1/policy.proto
  api/buf.lock
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/otelcollector/alertsreceiver/receiver.go
  pkg/otelcollector/config.go
  pkg/otelcollector/consts.go
Labels: size/XL

#1032 Fix PromQL component type to be Source
  pkg/policies/controlplane/components/promql/promql.go
Labels: size/XS

#1035 add images for FluxNinja kubernetes Pune recap blog
  docs/content/assets/img/fluxninja-at-kubernetes-pune/fluxninja-at-kubernetes-pune.png
Labels: size/XS

#1034 Fix alerts channel marshall & add resolve timeout helpers
  blueprints/examples/latency-gradient/example.jsonnet
  pkg/alerts/alert.go
  pkg/alerts/alert_test.go
  pkg/otelcollector/alertsexporter/exporter.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/alerter.go
Labels: size/S

#1031 Update OTEL to v0.67.0
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller/otel-component.go
  go.mod
  go.sum
  pkg/otelcollector/alertsexporter/config.go
  pkg/otelcollector/alertsexporter/factory.go
  pkg/otelcollector/alertsreceiver/config.go
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/enrichmentprocessor/enrichmentprocessor_suite_test.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/tracestologsprocessor/config.go
  pkg/otelcollector/tracestologsprocessor/factory.go
  pkg/otelcollector/tracestologsprocessor/processor.go
Labels: size/XL

#1036 rollupprocessor: Speed up key calculation
  pkg/otelcollector/rollupprocessor/key.go
  pkg/otelcollector/rollupprocessor/key_test.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/policies/flowcontrol/engine.go
Labels: size/L

#1037 Scrape otel metrics alongside aperture self scrape
  pkg/otelcollector/config.go
Labels: size/S

#1038 docs: remove blog assets
  docs/content/assets/img/adaptive-concurrency-limits/Signals-Dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/When-Aperture-is-protecting-service.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-light.png
  docs/content/assets/img/adaptive-concurrency-limits/demo-application.png
  docs/content/assets/img/adaptive-concurrency-limits/no-protection-setup.png
  docs/content/assets/img/adaptive-concurrency-limits/overall-view-grafana-dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-light.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-light.png
  docs/content/assets/img/fluxninja-at-kubernetes-pune/fluxninja-at-kubernetes-pune.png
Labels: size/XS

#1039 Fix linker in `make go-test`
  Makefile
Labels: size/XS

#1040 Changes for release 0.15.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1041 Cherry-picked changes for release v0.15.0-rc.2
  Makefile
  docs/content/assets/img/adaptive-concurrency-limits/Signals-Dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/When-Aperture-is-protecting-service.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/concurrency-limits-light.png
  docs/content/assets/img/adaptive-concurrency-limits/demo-application.png
  docs/content/assets/img/adaptive-concurrency-limits/no-protection-setup.png
  docs/content/assets/img/adaptive-concurrency-limits/overall-view-grafana-dashboard.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-dark.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-example-light.png
  docs/content/assets/img/adaptive-concurrency-limits/service-topology-light.png
  docs/content/assets/img/fluxninja-at-kubernetes-pune/fluxninja-at-kubernetes-pune.png
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
  pkg/otelcollector/config.go
Labels: size/M

#1030 Leader election per agent group
  pkg/etcd/client/client.go
  pkg/etcd/client/zz_generated.deepcopy.go
  pkg/etcd/election/election.go
Labels: size/L

#1043 License faq
  README.md
  docs/content/license-faq.md
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/dynamic-rate-limiting.md
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
Labels: size/M

#1047 Change license to GPLv3
  LICENSE
  README.md
  docs/content/license-faq.md
  docs/content/licensing-faq.md
  nfpm.yaml
  sdks/aperture-go/LICENSE.txt
  sdks/aperture-js/LICENSE.txt
Labels: size/XL

#1044 Handle error from fx.VisualizeError
  cmd/aperture-agent/agent.go
  cmd/aperture-controller/controller.go
Labels: size/S

#1049 Add image and description to Introduction page
  docs/content/introduction.md
Labels: size/XS

#1050 Changes for release v0.16.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1048 Improve deb packaging
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  nfpm.yaml
  packaging/aperture-agent.service
  packaging/aperture-agent.yaml
  packaging/post-install.sh
  pkg/config/config.go
Labels: size/M

#1051 Added steps for exposing the etcd and prometheus outside of the cluster
  docs/content/get-started/installation/controller.md
  manifests/charts/aperture-controller/README.md
  manifests/charts/aperture-controller/templates/_helpers.tpl
  manifests/charts/aperture-controller/templates/ingress.yaml
  manifests/charts/aperture-controller/values.yaml
Labels: size/L

#1052 Added CI steps to upload deb packages
  .circleci/config.yml
  .circleci/continue-workflows.yml
  .circleci/scripts/setup_gcloud.sh
Labels: size/L

#1053 Baremetal/VM agent package installation documentation
  docs/content/get-started/installation/agent/baremetal.md
  docs/content/get-started/installation/agent/envoy/_category_.yml
  docs/content/get-started/installation/agent/supported-platforms.md
Labels: size/L

#1055 Added support for generating rpm packages
  .circleci/continue-workflows.yml
  nfpm.yaml
Labels: size/M

#1056 Corrected package path in cloud artifacts upload
  .circleci/continue-workflows.yml
  nfpm.yaml
Labels: size/XS

#1057 Fixed the hyphen issue in rpm package name
  .circleci/continue-workflows.yml
  packaging/aperture-agent.yaml
Labels: size/XS

#1061 Added supported versions and minor docs changes for bare metal
  docs/content/get-started/installation/agent/agent.md
  docs/content/get-started/installation/agent/bare_metal.md
  docs/content/get-started/installation/agent/supported-platforms.md
Labels: size/M

#1062 Changes required for release v0.17.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1063 Fix baremetal package building
  .circleci/continue-workflows.yml
Labels: size/XS

#1064 Moved release bare metal packages to post-release pipeline
  .circleci/post-release.yaml
Labels: size/M

#1060 Update OTEL to v0.68.0
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller/otel-component.go
  go.mod
  go.sum
  pkg/otelcollector/alertsexporter/config.go
  pkg/otelcollector/alertsexporter/factory.go
  pkg/otelcollector/alertsreceiver/config.go
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/enrichmentprocessor/config.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/enrichmentprocessor/processor_test.go
  pkg/otelcollector/metricsprocessor/config.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/otelcollector.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/tracestologsprocessor/config.go
  pkg/otelcollector/tracestologsprocessor/factory.go
  tools/go/go.mod
  tools/go/go.sum
Labels: size/XL

#1054 Kubernetes Discovery: Cluster Domain
  pkg/discovery/kubernetes/kubernetes_discovery.go
Labels: size/M

#1046 Generic Cache for Control Points and other objects in the future
  cmd/aperture-agent/agent.go
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller.go
  pkg/cache/cache.go
  pkg/controlpointcache/control_point_cache.go
  pkg/otelcollector/metricsprocessor/config.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/flowcontrol/selectors/control-point-id.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
  test/aperture_suite_test.go
Labels: size/L

#1065 Fixed the separator issue in bare metal installation docs and replaced ghr with gh CLI
  .circleci/post-release.yaml
  docs/content/get-started/installation/agent/bare_metal.md
Labels: size/S

#1067 Changes from main to 0.17.x
  .circleci/continue-workflows.yml
  .circleci/post-release.yaml
  cmd/aperture-agent/agent.go
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller.go
  cmd/aperture-controller/controller/otel-component.go
  docs/content/get-started/installation/agent/bare_metal.md
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/controlpointcache/control_point_cache.go
  pkg/discovery/kubernetes/kubernetes_discovery.go
  pkg/otelcollector/alertsexporter/config.go
  pkg/otelcollector/alertsexporter/factory.go
  pkg/otelcollector/alertsreceiver/config.go
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/enrichmentprocessor/config.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/enrichmentprocessor/processor_test.go
  pkg/otelcollector/metricsprocessor/config.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/otelcollector/otelcollector.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/rollupprocessor/processor.go
  pkg/otelcollector/tracestologsprocessor/config.go
  pkg/otelcollector/tracestologsprocessor/factory.go
  pkg/policies/flowcontrol/selectors/control-point-id.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
  test/aperture_suite_test.go
  tools/go/go.mod
  tools/go/go.sum
Labels: size/XL

#1070 flowcontrol: preview api
  api/Makefile
  api/aperture/flowcontrol/preview/v1/preview.proto
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.gw.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_deepcopy.gen.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_grpc.pb.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/agent.md
  docs/gen/config/agent/config-swagger.yaml
  operator/api/agent/v1alpha1/agent_types.go
  operator/api/agent/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  pkg/net/grpc/server.go
  pkg/net/grpc/validator.go
  pkg/policies/flowcontrol/config-operations.go
  pkg/policies/flowcontrol/engine.go
  pkg/policies/flowcontrol/iface/classifier.go
  pkg/policies/flowcontrol/iface/engine.go
  pkg/policies/flowcontrol/iface/label-preview.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/envoy/provide.go
  pkg/policies/flowcontrol/service/preview/label-preview.go
  pkg/policies/flowcontrol/service/preview/provide.go
  pkg/policies/flowcontrol/service/preview/zz_generated.deepcopy.go
  pkg/policies/flowcontrol/service/provide.go
  pkg/policies/mocks/mock_engine.go
  pkg/watchdog/policy.go
  pkg/watchdog/watchdog.go
  playground/tanka/apps/aperture-agent/mixins.libsonnet
  sdks/aperture-js/proto/flowcontrol/check/v1/check.proto
  sdks/aperture-js/sdk/consts.js
Labels: size/XL
