Repository fluxninja/aperture, pull requests merged in 2022-11, with the labels that each got.

#875 panichandler: process panic handlers in the same go routine
  pkg/panichandler/panichandler.go
  plugins/service/aperture-plugin-sentry/sentry/sentrywriter.go
Labels: size/M

#873 Added support for sidecar mode in istioconfig chart and added installation docs
  docs/content/get-started/installation/agent/envoy/istio.md
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  manifests/charts/istioconfig/README.md
  manifests/charts/istioconfig/templates/envoy_filter.yaml
  manifests/charts/istioconfig/values.yaml
Labels: size/L

#872 Set minimum interval to 1s for timeseries in Grafana
  blueprints/examples/latency-gradient/gen/dashboards/example.json
  blueprints/lib/1.0/blueprints/latency-gradient/dashboard.libsonnet
Labels: size/XS

#876 Invalid signals telemetry
  blueprints/examples/latency-gradient/gen/dashboards/example.json
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/dashboard.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  blueprints/lib/1.0/blueprints/signals-dashboard/dashboard.libsonnet
  docs/content/get-started/policies/assets/monitoring/signals-dashboard.json
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/metrics/schema.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/policies/controlplane/runtime/circuit.go
  pkg/policies/dataplane/resources/fluxmeter/flux-meter.go
Labels: size/XXL

#877 Corrected typo in the docs
  docs/content/get-started/installation/agent/envoy/istio.md
Labels: size/XS

#851 Removed extra space from `Too many open files "warning"` FAQ section
  docs/content/get-started/playground.md
Labels: size/S

#887 Docs - Tip about applying FluxMeter to a single workload
  docs/content/tutorials/signal-processing/detecting-overload.md
Labels: size/S

#888 docs: add demo video links
  .github/CODEOWNERS
  README.md
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
Labels: size/S

#890 Fix Wrong link associated in playground docs
  docs/content/get-started/playground.md
Labels: size/XS

#892 Prepare for v0.9.0 release
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#881 Speed up ser/deserialization of CheckResponse in envoy authz
  pkg/otelcollector/helpers.go
  pkg/policies/flowcontrol/api/envoy/authz.go
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/TrafficFlow.java
Labels: size/M

#878 Document Prometheus metrics and OLAP Flow events
  README.md
  docs/content/references/flow-events/_category_.yaml
  docs/content/references/flow-events/flow-events.md
  docs/content/references/metrics/_category_.yaml
  docs/content/references/metrics/agent.md
  docs/content/references/metrics/common.md
  docs/content/references/metrics/controller.md
  pkg/otelcollector/consts.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor.go
Labels: size/L

#897 Fix metrics docs
  docs/content/concepts/flow-control/flow-label.md
  docs/content/references/flow-events/_category_.yaml
  docs/content/references/flow-events/flow-events.md
  docs/content/references/metrics/_category_.yaml
  docs/content/references/prometheus-metrics/_category_.yaml
  docs/content/references/prometheus-metrics/agent.md
  docs/content/references/prometheus-metrics/common.md
  docs/content/references/prometheus-metrics/controller.md
Labels: size/L

#893 Alerts pipelines
  .circleci/continue-workflows.yml
  cmd/aperture-agent/Dockerfile
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-agent/agent/provider.go
  cmd/aperture-controller/Dockerfile
  cmd/aperture-controller/controller/otel-component.go
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  go.mod
  go.sum
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/alerts/alert.go
  pkg/alerts/alert_test.go
  pkg/alerts/alerter.go
  pkg/alerts/alerts_suite_test.go
  pkg/alerts/provide.go
  pkg/alerts/zz_generated.deepcopy.go
  pkg/otelcollector/alertsreceiver/config.go
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/alertsreceiver/processor.go
  pkg/otelcollector/config.go
  pkg/otelcollector/consts.go
  pkg/otelcollector/zz_generated.deepcopy.go
  pkg/platform/platform.go
  plugins/service/aperture-plugin-fluxninja/otel/otel_test.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/XL

#904 Update aperture-js fingerprint
  .circleci/continue-workflows.yml
  sdks/aperture-js/sdk/client.js
Labels: size/XS

#907 Add pprof-related files to .gitignore
  .gitignore
Labels: size/XS

#906 Remove unused CheckResponse.Error
  api/aperture/flowcontrol/check/v1/check.proto
  api/gen/proto/go/aperture/flowcontrol/check/v1/check.pb.go
  docs/content/assets/openapiv2/aperture.swagger.yaml
  pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/flowcontrol/resources/classifier/classification-engine.go
  pkg/policies/flowcontrol/resources/classifier/classifier_test.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/check/metrics.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  sdks/aperture-go/gen/proto/flowcontrol/check/v1/check.pb.go
  sdks/aperture-java/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckProto.java
  sdks/aperture-java/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckResponse.java
  sdks/aperture-java/src/main/java/com/fluxninja/generated/aperture/flowcontrol/check/v1/CheckResponseOrBuilder.java
  sdks/aperture-js/proto/check/v1/check.proto
Labels: size/XXL

#908 playground grafana: Set scrape interval in prometheus data source
  playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/XS

#913 Add ENV variable for armeria client and server
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/ArmeriaClient.java
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/example/ArmeriaServer.java
Labels: size/M

#914 Dry run docs and link versioning
  docs/content/get-started/playground.md
  docs/content/get-started/policies/blueprints.md
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
Labels: size/M

#909 Fixed deployment sync issue for CRDs
  .circleci/config.yml
Labels: size/XS

#916 Prepare for release 0.10.0
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#917 Fixed Helm version check error on release
  .circleci/scripts/helm_release.sh
Labels: size/XS

#920 Docs: Aperture version is self-contained inside docs
  docs/content/get-started/policies/blueprints.md
  docs/content/introduction.md
Labels: size/S

#921 Learning period via EMA warm up window
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/ema.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/components/ema.go
Labels: size/XXL

#923 Fixed multiple definition error on build
  .circleci/config.yml
Labels: size/XS

#924 Cherry-picked changes for release 0.10.0-rc.2
  .circleci/config.yml
  .circleci/scripts/helm_release.sh
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/_gen/v1/ema.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/get-started/policies/blueprints.md
  docs/content/introduction.md
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/components/ema.go
Labels: size/XXL

#927 Docs: Fix version used for link templating
  docs/content/introduction.md
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
Labels: size/M

#928 Make gradle generate a JAR file with all dependencies included
  .circleci/continue-workflows.yml
  sdks/aperture-java/build.gradle.kts
  sdks/aperture-java/gradle/wrapper/gradle-wrapper.jar
  sdks/aperture-java/gradle/wrapper/gradle-wrapper.properties
  sdks/aperture-java/gradlew
  sdks/aperture-java/gradlew.bat
  sdks/aperture-java/settings.gradle.kts
Labels: size/M

#930 Fixed the operator tests getting skipped issue
  operator/controllers/agent/agent_suite_test.go
  operator/controllers/agent/config_test.tpl
  operator/controllers/controller/config_test.tpl
  operator/controllers/controller/controller_suite_test.go
  operator/controllers/mutatingwebhook/mutatingwebhook_suite_test.go
  operator/controllers/mutatingwebhook/reconciler_test.go
  operator/controllers/namespace/namespace_suite_test.go
  operator/controllers/namespace/reconciler_test.go
Labels: size/XL

#910 Make otel debug and healthcheck ports configurable
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  operator/controllers/agent/config_test.tpl
  operator/controllers/agent/configmaps_test.go
  operator/controllers/agent/daemonset.go
  operator/controllers/agent/daemonset_test.go
  operator/controllers/constants.go
  operator/controllers/controller/config_test.tpl
  operator/controllers/controller/configmaps_test.go
  operator/controllers/controller/deployment.go
  operator/controllers/controller/deployment_test.go
  operator/controllers/mutatingwebhook/agent_pod.go
  operator/controllers/mutatingwebhook/agent_pod_test.go
  pkg/otelcollector/config.go
  pkg/otelcollector/zz_generated.deepcopy.go
  plugins/service/aperture-plugin-fluxninja/otel/provide.go
Labels: size/XL

#932 Update opentelemetry exporter dependency
  sdks/aperture-java/build.gradle.kts
Labels: size/XS

#929 Improve visibility of sampled logs
  pkg/alerts/alert.go
  pkg/log/log.go
  pkg/log/log_suite_test.go
  pkg/log/samplers.go
  pkg/log/samplers_test.go
  pkg/otelcollector/alertsreceiver/processor.go
  pkg/otelcollector/helpers.go
  pkg/otelcollector/metricsprocessor/internal/check_response_labels.go
  pkg/otelcollector/metricsprocessor/internal/sdk_labels.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/flowcontrol/actuators/concurrency/load-actuator.go
  pkg/policies/flowcontrol/resources/classifier/classification-engine.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  pkg/watchdog/watchdog.go
Labels: size/L

#935 Move aperture-java publishing jobs to SDK
  .circleci/continue-workflows.yml
  sdks/aperture-java/.circleci/config.yml
  sdks/aperture-java/.circleci/continue-workflows.yml
Labels: size/L

#936 Update Java SDK snapshot version to 0.4.0
  sdks/aperture-java/version.gradle.kts
Labels: size/XS

#940 Fix failing to start flow when passing null labels map
  sdks/aperture-java/src/main/java/com/fluxninja/aperture/sdk/ApertureSDK.java
Labels: size/XS

#942 Downgrade slf4j dependency
  sdks/aperture-java/build.gradle.kts
Labels: size/XS

#941 Relocate all packages when creating a shadow jar
  sdks/aperture-java/build.gradle.kts
Labels: size/S

#931 Make Gradle build java SDK compatible with JDK 1.8
  sdks/aperture-java/build.gradle.kts
Labels: size/XS

#943 Start warning on entity lookup failure in authz and flowcontrol
  pkg/log/log.go
  pkg/log/samplers.go
  pkg/net/grpc/helpers.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  pkg/policies/flowcontrol/service/envoy/authz_test.go
Labels: size/L

#933 Added the functionality to check for the minimum supported kubernetes version
  .codespellignore
  operator/controllers/agent/reconciler.go
  operator/controllers/constants.go
  operator/controllers/controller/reconciler.go
  operator/main.go
Labels: size/M

#939 Alerter Component
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/lib/1.0/_gen/v1/alerter.libsonnet
  blueprints/lib/1.0/_gen/v1/alerterins.libsonnet
  blueprints/lib/1.0/_gen/v1/component.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller/otel-component.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/alerts/alert.go
  pkg/alerts/alerter.go
  pkg/alerts/provide.go
  pkg/platform/platform.go
  pkg/policies/controlplane/component-factory.go
  pkg/policies/controlplane/component-factory_test.go
  pkg/policies/controlplane/components/alerter.go
  pkg/policies/controlplane/policy-factory.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
  test/aperture_suite_test.go
Labels: size/L

#946 `git push` retry for Helm-release script
  .circleci/scripts/helm_release.sh
Labels: size/S

#911 Add GraphQL Demoapp
  api/aperture/policy/language/v1/classifier.proto
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  blueprints/examples/rate-limiter/gen/graph/graph.svg
  blueprints/examples/rate-limiter/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/rate-limiter/config.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/policy.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting-counter.png
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.yaml
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/gen/policy/policy.yaml
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  pkg/policies/flowcontrol/actuators/rate/rate-limiter.go
  pkg/policies/flowcontrol/engine.go
  pkg/policies/flowcontrol/iface/limiter.go
  pkg/policies/mocks/mock_limiter.go
  playground/Tiltfile
  playground/graphql_demo_app/Dockerfile
  playground/graphql_demo_app/go.mod
  playground/graphql_demo_app/go.sum
  playground/graphql_demo_app/gqlgen.yml
  playground/graphql_demo_app/graph/generated/generated.go
  playground/graphql_demo_app/graph/model/models_gen.go
  playground/graphql_demo_app/graph/model/todo.go
  playground/graphql_demo_app/graph/resolver.go
  playground/graphql_demo_app/graph/schema.graphqls
  playground/graphql_demo_app/graph/schema.resolvers.go
  playground/graphql_demo_app/server.go
  playground/graphql_demo_app/tools/tools.go
  playground/load_generator/scenarios/graphql_load_test.js
  playground/tanka/apps/graphql-demoapp/main.jsonnet
  playground/tanka/apps/graphql-demoapp/mixins.libsonnet
  playground/tanka/charts/graphql-demo-app/.helmignore
  playground/tanka/charts/graphql-demo-app/Chart.yaml
  playground/tanka/charts/graphql-demo-app/templates/_helpers.tpl
  playground/tanka/charts/graphql-demo-app/templates/deployment.yaml
  playground/tanka/charts/graphql-demo-app/templates/service.yaml
  playground/tanka/charts/graphql-demo-app/templates/serviceaccount.yaml
  playground/tanka/charts/graphql-demo-app/values.yaml
  playground/tanka/lib/apps/graphql-demoapp/main.libsonnet
Labels: size/XXL

#953 Remove debug log
  pkg/discovery/kubernetes/kubernetes_discovery.go
  pkg/peers/peers.go
Labels: size/XS

#952 docs : Fix typo in the reference section for controller
  docs/content/references/configuration/controller.md
Labels: size/XS

#954 Fixed pre-commit failure on controller config docs
  docs/gen/config/controller/metadata
Labels: size/XS

#956 Avoid discarding whole batch if processing single log record fails
  .codespellignore
  pkg/otelcollector/helpers.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/rollupprocessor/processor.go
Labels: size/M

#958 otelcollector/helpers: Remove unused fallibility from iterate helpers
  pkg/otelcollector/enrichmentprocessor/processor.go
  pkg/otelcollector/helpers.go
  pkg/otelcollector/tracestologsprocessor/processor.go
Labels: size/M

#959 Changed the cloud beta link from waitlist to sign-in
  docs/content/cloud/cloud.md
Labels: size/XS

#962 flowcontrol: Remove spammy "Running limiters with labels" log
  pkg/policies/flowcontrol/engine.go
Labels: size/XS

#963 Cherry-picked changes for release 0.11.1-rc.1
  docs/content/cloud/cloud.md
  pkg/policies/flowcontrol/engine.go
Labels: size/XS

#960 Upgrade OTEL to v0.64.0
  go.mod
  go.sum
Labels: size/L

#967 Don't use deprecated stuff from OTEL
  pkg/otelcollector/alertsreceiver/config.go
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/rollupprocessor/config.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/tracestologsprocessor/config.go
  pkg/otelcollector/tracestologsprocessor/factory.go
  pkg/otelcollector/tracestologsprocessor/processor.go
Labels: size/M

#964 Add control points handling
  api/aperture/plugins/fluxninja/v1/heartbeat.proto
  api/buf.lock
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat.pb.json.go
  api/gen/proto/go/aperture/plugins/fluxninja/v1/heartbeat_deepcopy.gen.go
  cmd/aperture-agent/agent.go
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller.go
  docs/content/assets/openapiv2/aperture.swagger.yaml
  pkg/controlpointcache/control_point_cache.go
  pkg/otelcollector/metricsprocessor/config.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/metricsprocessor/processor.go
  pkg/otelcollector/metricsprocessor/processor_test.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
  test/aperture_suite_test.go
Labels: size/L

#968 Upgrade OTEL to v0.66.0
  go.mod
  go.sum
  pkg/otelcollector/alertsreceiver/factory.go
  pkg/otelcollector/enrichmentprocessor/factory.go
  pkg/otelcollector/enrichmentprocessor/processor_test.go
  pkg/otelcollector/metricsprocessor/factory.go
  pkg/otelcollector/rollupprocessor/factory.go
  pkg/otelcollector/tracestologsprocessor/factory.go
Labels: size/L

#971 Prepare for release v.0.12.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#972 Update Golang deps
  go.mod
  go.sum
  operator/controllers/agent/mutating_webhook_configuration.go
  operator/controllers/controller/validating_webhook_configuration.go
  operator/controllers/mutatingwebhook/mutating_webhook_configuration.go
  operator/controllers/utils.go
  pkg/policies/flowcontrol/service/envoy/authz.go
Labels: size/L

#976 Cherry-picked changes for release 0.12.0-rc.2
  api/aperture/policy/language/v1/classifier.proto
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  go.mod
  go.sum
  operator/controllers/agent/mutating_webhook_configuration.go
  operator/controllers/controller/validating_webhook_configuration.go
  operator/controllers/mutatingwebhook/mutating_webhook_configuration.go
  operator/controllers/utils.go
  pkg/policies/controlplane/validator_test.go
  pkg/policies/flowcontrol/service/envoy/authz.go
Labels: size/XL

#977 Hide postable alert object, add options to alert
  pkg/alerts/alert.go
  pkg/alerts/alert_test.go
  pkg/policies/controlplane/components/alerter.go
Labels: size/L

#966 Alertmanager Exporter
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller/otel-component.go
  docs/gen/config/agent/config-swagger.yaml
  docs/gen/config/controller/config-swagger.yaml
  go.mod
  go.sum
  operator/api/common/common_types.go
  operator/api/common/zz_generated.deepcopy.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  pkg/alertmanager/client/client.go
  pkg/alertmanager/client/zz_generated.deepcopy.go
  pkg/alertmanager/provide.go
  pkg/net/http/client.go
  pkg/otelcollector/alertsexporter/config.go
  pkg/otelcollector/alertsexporter/exporter.go
  pkg/otelcollector/alertsexporter/factory.go
  pkg/otelcollector/config.go
  pkg/otelcollector/consts.go
  pkg/platform/platform.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/XL
