Repository fluxninja/aperture, pull requests merged in 2023-01, with the labels that each got.

#1085 docs: flow label preview api
  README.md
  docs/content/cloud/cloud.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
Labels: size/M

#1087 Changes from main to 0.17.x
  README.md
  api/Makefile
  api/aperture/flowcontrol/preview/v1/preview.proto
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.gw.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_deepcopy.gen.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_grpc.pb.go
  cmd/aperture-agent/agent.go
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/cloud/cloud.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/references/configuration/agent.md
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
  docs/gen/config/agent/config-swagger.yaml
  operator/api/agent/v1alpha1/agent_types.go
  operator/api/agent/v1alpha1/zz_generated.deepcopy.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  pkg/net/grpc/server.go
  pkg/net/grpc/validator.go
  pkg/policies/flowcontrol/config-operations.go
  pkg/policies/flowcontrol/engine.go
  pkg/policies/flowcontrol/iface/classifier.go
  pkg/policies/flowcontrol/iface/engine.go
  pkg/policies/flowcontrol/iface/label-preview.go
  pkg/policies/flowcontrol/service/check/check.go
  pkg/policies/flowcontrol/service/envoy/provide.go
  pkg/policies/flowcontrol/service/preview/label-preview.go
  pkg/policies/flowcontrol/service/preview/provide.go
  pkg/policies/flowcontrol/service/preview/zz_generated.deepcopy.go
  pkg/policies/flowcontrol/service/provide.go
  pkg/policies/mocks/mock_engine.go
  pkg/watchdog/policy.go
  pkg/watchdog/watchdog.go
  playground/tanka/apps/aperture-agent/mixins.libsonnet
  sdks/aperture-js/proto/flowcontrol/check/v1/check.proto
  sdks/aperture-js/sdk/consts.js
Labels: size/XL

#1092 Update ci executor
  .circleci/config.yml
  .circleci/continue-workflows.yml
Labels: size/XS

#1094 Remove spammy debug log
  pkg/config/validator.go
Labels: size/XS

#1096 Fix pre-commit error in graphql_demo_app
  playground/graphql_demo_app/graph/schema.resolvers.go
Labels: size/S

#1097 update remote-docker-version in CI
  .circleci/continue-workflows.yml
Labels: size/XS

#1098 Changes for release v0.18.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1099 Exposed the buf build username in environment variables
  .circleci/post-release.yaml
Labels: size/XS

#1100 Cherry-picked changes from main for v0.18.0-rc.2
  .circleci/post-release.yaml
Labels: size/XS

#1104 Remove ControlPointCache dependency in Controller
  cmd/aperture-agent/agent.go
  cmd/aperture-agent/agent/otel-component.go
  cmd/aperture-controller/controller.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/heartbeats.go
  plugins/service/aperture-plugin-fluxninja/heartbeats/provide.go
Labels: size/S

#1101 Updated SSH Keys for other repos
  .circleci/config.yml
  .circleci/continue-workflows.yml
Labels: size/M

#1106 Tutorials: Re-order YAML and Jsonnet tabs
  docs/content/tutorials/flow-control/basic-concurrency-limiting.md
  docs/content/tutorials/flow-control/dynamic-rate-limiting.md
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/content/tutorials/flow-control/static-rate-limiting.md
  docs/content/tutorials/flow-control/workload-prioritization.md
  docs/content/tutorials/signal-processing/detecting-overload.md
Labels: size/M

#1107 Docs: Applying Policies section
  docs/content/assets/scripts/version-code.js
  docs/content/get-started/policies/applying-policies.md
  docs/content/get-started/policies/blueprints.md
  docs/content/get-started/policies/dynamic-configuration.md
  docs/content/get-started/policies/monitoring.md
Labels: size/M

#1103 Update aperture on customer demo cluster when changes merged to main
  .circleci/continue-workflows.yml
  .circleci/post-release.yaml
  .circleci/scripts/update_environment.sh
  .opsninja.yaml
Labels: size/L

#1088 Cleaned up RBAC permissions in operator for agent and controller
  manifests/charts/aperture-agent/templates/rbac.yaml
  manifests/charts/aperture-controller/templates/rbac.yaml
  operator/config/rbac/role.yaml
  operator/controllers/agent/clusterrole.go
  operator/controllers/agent/clusterrole_test.go
  operator/controllers/agent/config_test.tpl
  operator/controllers/agent/configmaps_test.go
  operator/controllers/agent/reconciler.go
  operator/controllers/agent/reconciler_test.go
  operator/controllers/controller/clusterrole.go
  operator/controllers/controller/clusterrole_test.go
  operator/controllers/controller/reconciler.go
  operator/controllers/controller/reconciler_test.go
Labels: size/XL

#1058 Add Differentiator component
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/lib/1.0/_gen/v1/component.libsonnet
  blueprints/lib/1.0/_gen/v1/differentiator.libsonnet
  blueprints/lib/1.0/_gen/v1/differentiatorins.libsonnet
  blueprints/lib/1.0/_gen/v1/differentiatorouts.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/policies/controlplane/circuitfactory/component-factory.go
  pkg/policies/controlplane/components/differentiator.go
  pkg/utils/helpers.go
  playground/tanka/apps/aperture-controller/mixins.libsonnet
Labels: size/L

#1108 Corrected static rate limiting policy on docs
  docs/content/get-started/policies/applying-policies.md
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/static-rate-limiting/static-rate-limiting.yaml
Labels: size/M

#1110 Docs: Update Applying Policies section
  docs/content/get-started/policies/applying-policies.md
Labels: size/S

#1111 Updated apply policy section on controller installation page
  docs/content/get-started/installation/controller.md
  docs/content/get-started/policies/applying-policies.md
Labels: size/S

#1114 Fixed the reconciler errors in operator due to ClusterRole name change
  operator/controllers/agent/reconciler.go
  operator/controllers/controller/reconciler.go
Labels: size/S

#1115 Updated deprecated methods in operator
  operator/controllers/agent/configmaps_test.go
  operator/controllers/agent/daemonset_test.go
  operator/controllers/agent/mutating_webhook_configuration_test.go
  operator/controllers/agent/secrets_test.go
  operator/controllers/agent/serviceaccount_test.go
  operator/controllers/agent/services_test.go
  operator/controllers/controller/configmaps_test.go
  operator/controllers/controller/deployment_test.go
  operator/controllers/controller/secrets_test.go
  operator/controllers/controller/serviceaccount_test.go
  operator/controllers/controller/services_test.go
  operator/controllers/controller/validating_webhook_configuration_test.go
  operator/controllers/mutate_func_test.go
  operator/controllers/mutatingwebhook/agent_pod_test.go
  operator/controllers/mutatingwebhook/mutating_webhook_configuration_test.go
  operator/controllers/mutatingwebhook/reconciler_test.go
  operator/controllers/utils_test.go
Labels: size/L

#1109 Add 'Flow Control' section under 'Getting Started' in docs
  api/aperture/policy/language/v1/fluxmeter.proto
  api/gen/proto/go/aperture/policy/language/v1/fluxmeter.pb.go
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-control.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/get-started/flow-control/_category_.yaml
  docs/content/get-started/flow-control/envoy/_category_.yaml
  docs/content/get-started/flow-control/envoy/istio.md
  docs/content/get-started/flow-control/sdk/_category_.yaml
  docs/content/get-started/flow-control/sdk/aperture-java.md
  docs/content/get-started/flow-control/sdk/aperture-js.md
  docs/content/get-started/flow-control/sdk/apeture-go.md
  docs/content/get-started/installation/agent/envoy/_category_.yml
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/policies/_category_.yml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting-counter.png
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting-demo.png
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.jsonnet
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/graphql-rate-limiting/graphql-rate-limiting.yaml
  docs/content/tutorials/flow-control/graphql-rate-limiting.md
  docs/gen/policy/policy.yaml
Labels: size/L

#1116 Renamed cloud to ARC and added plugin config example
  api/aperture/policy/language/v1/classifier.proto
  api/gen/proto/go/aperture/policy/language/v1/classifier.pb.go
  docs/content/arc/_category_.yml
  docs/content/arc/arc.md
  docs/content/arc/plugin.md
  docs/content/assets/diagrams/architecture/fluxninja.mmd
  docs/content/assets/diagrams/architecture/fluxninja.mmd.md5sum
  docs/content/assets/diagrams/architecture/fluxninja.mmd.png
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/cloud/plugin.md
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/get-started/installation/agent/bare_metal.md
  docs/content/get-started/installation/agent/kubernetes/daemonset.md
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  docs/content/get-started/installation/controller.md
  docs/content/references/configuration/agent.md
  docs/content/references/configuration/controller.md
  docs/content/references/configuration/policy.md
  docs/content/references/flow-events/flow-events.md
  docs/gen/config/aperture-plugin-fluxninja/plugin-swagger.yaml
  docs/gen/policy/policy.yaml
  manifests/charts/aperture-agent/templates/_helpers.tpl
  manifests/charts/aperture-agent/values.yaml
  manifests/charts/aperture-controller/templates/_helpers.tpl
  manifests/charts/aperture-controller/values.yaml
  operator/api/common/common_types.go
  operator/config/crd/bases/fluxninja.com_agents.yaml
  operator/config/crd/bases/fluxninja.com_controllers.yaml
  plugins/service/aperture-plugin-fluxninja/main.go
  plugins/service/aperture-plugin-fluxninja/pluginconfig/pluginconfig.go
Labels: size/L

#1120 Prepare for release v0.19.x
  docs/content/introduction.md
  manifests/charts/aperture-agent/Chart.yaml
  manifests/charts/aperture-controller/Chart.yaml
  manifests/charts/istioconfig/Chart.yaml
Labels: size/S

#1121 Corrected resource dependency in tilt file when only controller is started
  playground/Tiltfile
Labels: size/XS

#1124 docs: validate documented policies even when they don't change
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.jsonnet
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.yaml
  docs/tools/jsonnet/generate_jsonnet.sh
Labels: size/XS

#1125 update architecture diagrams
  README.md
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.md5sum
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.png
  docs/content/assets/diagrams/architecture/aperture-k8s.mmd.svg
  docs/content/assets/diagrams/architecture/aperture.mmd
  docs/content/assets/diagrams/architecture/aperture.mmd.md5sum
  docs/content/assets/diagrams/architecture/aperture.mmd.png
  docs/content/assets/diagrams/architecture/aperture.mmd.svg
  docs/content/assets/diagrams/architecture/architecture_simple.mmd
  docs/content/assets/diagrams/architecture/architecture_simple.mmd.md5sum
  docs/content/assets/diagrams/architecture/architecture_simple.mmd.png
  docs/content/assets/diagrams/architecture/architecture_simple.mmd.svg
  docs/content/assets/diagrams/architecture/fluxninja.mmd
  docs/content/assets/diagrams/architecture/fluxninja.mmd.md5sum
  docs/content/assets/diagrams/architecture/fluxninja.mmd.png
  docs/content/assets/diagrams/architecture/fluxninja.mmd.svg
  docs/content/assets/gen/introduction/architecture_simple.mmd.md5sum
  docs/content/assets/gen/introduction/architecture_simple.mmd.png
  docs/content/assets/gen/introduction/architecture_simple.mmd.svg
  docs/content/introduction.md
  docs/tools/mermaid/mermaid-theme.json
  go.mod
  go.sum
  pkg/alertmanager/client/client.go
  requirements.txt
  scripts/manage_tools.sh
Labels: size/L

#1126 update readme
  README.md
Labels: size/XS

#1130 flowcontrol: preview http requests
  .gitignore
  api/aperture/flowcontrol/preview/v1/preview.proto
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.gw.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.json.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_deepcopy.gen.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview_grpc.pb.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/concepts/flow-control/flow-classifier.md
  pkg/policies/flowcontrol/engine.go
  pkg/policies/flowcontrol/iface/label-preview.go
  pkg/policies/flowcontrol/iface/preview.go
  pkg/policies/flowcontrol/resources/classifier/classification-engine.go
  pkg/policies/flowcontrol/resources/classifier/classifier_test.go
  pkg/policies/flowcontrol/service/envoy/authz.go
  pkg/policies/flowcontrol/service/preview/flow-preview-service.go
  pkg/policies/flowcontrol/service/preview/http-request-preview.go
  pkg/policies/flowcontrol/service/preview/label-preview.go
Labels: size/XL

#1131 flowcontrol: allow passing flow label matcher in preview requests
  api/aperture/flowcontrol/preview/v1/preview.proto
  api/aperture/policy/language/v1/selector.proto
  api/buf.gen.aperture.yaml
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.go
  api/gen/proto/go/aperture/flowcontrol/preview/v1/preview.pb.gw.go
  api/gen/proto/go/aperture/policy/language/v1/selector.pb.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-label.md
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/workload-prioritization.md
  docs/gen/policy/policy.yaml
  pkg/policies/flowcontrol/service/preview/http-request-preview.go
  pkg/policies/flowcontrol/service/preview/label-preview.go
Labels: size/XXL

#1132 docs: add links to introspection APIs for flowcontrol preview
  .gitignore
  docs/content/concepts/flow-control/flow-classifier.md
  docs/content/concepts/flow-control/flow-label.md
Labels: size/S

#1133 tutorial: remove sink from overload detection turotial
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/lib/1.0/_gen/v1/alerter.libsonnet
  blueprints/lib/1.0/_gen/v1/alerterins.libsonnet
  blueprints/lib/1.0/_gen/v1/component.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/sink.libsonnet
  blueprints/lib/1.0/_gen/v1/sinkins.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.jsonnet
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.md5sum
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.png
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.mmd.svg
  docs/content/tutorials/signal-processing/assets/detecting-overload/detecting-overload.yaml
  docs/gen/policy/policy.yaml
  pkg/policies/controlplane/circuitfactory/component-factory.go
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
  pkg/policies/controlplane/components/alerter.go
  pkg/policies/controlplane/components/sink.go
  pkg/policies/controlplane/validator.go
Labels: size/L

#1134 alerter: do not create load shed actuator alerts if no config provided
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  docs/gen/policy/policy.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
  pkg/policies/controlplane/components/actuators/concurrency/load-actuator.go
Labels: size/XL

#1113 Add getting started SDK docs
  docs/content/get-started/flow-control/sdk/_category_.yml
  docs/content/get-started/flow-control/sdk/aperture-java.md
  docs/content/get-started/flow-control/sdk/aperture-js.md
  docs/content/get-started/flow-control/sdk/apeture-go.md
  docs/content/get-started/flow-control/sdk/go/_category_.yml
  docs/content/get-started/flow-control/sdk/go/manual.md
  docs/content/get-started/flow-control/sdk/java/_category_.yml
  docs/content/get-started/flow-control/sdk/java/manual.md
  docs/content/get-started/flow-control/sdk/java/middleware.md
  docs/content/get-started/flow-control/sdk/javascript/_category_.yml
  docs/content/get-started/flow-control/sdk/javascript/manual.md
  docs/content/get-started/flow-control/sdk/overview.md
Labels: size/L

#1139 Cherrypick - Add getting started SDK docs (#1113)
  docs/content/get-started/flow-control/sdk/_category_.yml
  docs/content/get-started/flow-control/sdk/aperture-java.md
  docs/content/get-started/flow-control/sdk/aperture-js.md
  docs/content/get-started/flow-control/sdk/apeture-go.md
  docs/content/get-started/flow-control/sdk/go/_category_.yml
  docs/content/get-started/flow-control/sdk/go/manual.md
  docs/content/get-started/flow-control/sdk/java/_category_.yml
  docs/content/get-started/flow-control/sdk/java/manual.md
  docs/content/get-started/flow-control/sdk/java/middleware.md
  docs/content/get-started/flow-control/sdk/javascript/_category_.yml
  docs/content/get-started/flow-control/sdk/javascript/manual.md
  docs/content/get-started/flow-control/sdk/overview.md
Labels: size/L

#922 Enable race detection for agent and controller using `--race` flag in tilt dev environment
  .circleci/continue-workflows.yml
  cmd/aperture-agent/Dockerfile
  cmd/aperture-controller/Dockerfile
  pkg/info/build.sh
  pkg/plugins/build.sh
  playground/Tiltfile
Labels: size/M

#1089 Added support for changing agent installation mode without re-creation of CR
  docs/content/get-started/installation/agent/kubernetes/sidecar.md
  operator/controllers/agent/daemonset.go
  operator/controllers/agent/daemonset_test.go
  operator/controllers/agent/hook.go
  operator/controllers/agent/hook_test.go
  operator/controllers/agent/old_hook_test.tpl
  operator/controllers/agent/reconciler.go
  operator/controllers/agent/reconciler_test.go
  operator/controllers/constants.go
Labels: size/L

#1142 Add resolve timeout to Concurrency Limiter alerts
  blueprints/examples/latency-gradient/gen/graph/graph.dot
  blueprints/examples/latency-gradient/gen/graph/graph.svg
  blueprints/examples/latency-gradient/gen/policies/example.yaml
  blueprints/lib/1.0/blueprints/latency-gradient/README.md
  blueprints/lib/1.0/blueprints/latency-gradient/config.libsonnet
  blueprints/lib/1.0/blueprints/latency-gradient/policy.libsonnet
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/basic-concurrency-limiting/basic-concurrency-limiting.yaml
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.md5sum
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.png
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.mmd.svg
  docs/content/tutorials/flow-control/assets/dynamic-rate-limiting/dynamic-rate-limiting.yaml
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.md5sum
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.png
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.mmd.svg
  docs/content/tutorials/flow-control/assets/workload-prioritization/workload-prioritization.yaml
  operator/config/samples/fluxninja.com_v1alpha1_policy.yaml
Labels: size/XL

#1145 Add README for sdk-validator
  cmd/sdk-validator/README.md
Labels: size/M

#1095 Update license
  LICENSE
  README.md
  docs/content/licensing-faq.md
Labels: size/XL

#1152 docs: restructure observability reference
  docs/content/arc/plugin.md
  docs/content/get-started/policies/applying-policies.md
  docs/content/references/observability/_category_.yaml
  docs/content/references/observability/flow-metrics/_category_.yaml
  docs/content/references/observability/flow-metrics/flow-metrics.md
  docs/content/references/observability/prometheus-metrics/_category_.yaml
  docs/content/references/observability/prometheus-metrics/agent.md
  docs/content/references/observability/prometheus-metrics/common.md
  docs/content/references/observability/prometheus-metrics/controller.md
Labels: size/M

#1143 Added dashboard for rate limit policy
  blueprints/examples/rate-limiter/gen/dashboards/example.json
  blueprints/lib/1.0/blueprints/rate-limiter/README.md
  blueprints/lib/1.0/blueprints/rate-limiter/bundle.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/config.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/dashboard.libsonnet
  blueprints/lib/1.0/blueprints/rate-limiter/metadata.yaml
  blueprints/lib/1.0/blueprints/rate-limiter/rate-limiter.libsonnet
  playground/tanka/lib/apps/aperture-grafana/main.libsonnet
Labels: size/L

#1156 Make java agent shadow jar maven-publishable
  sdks/aperture-java/javaagent/build.gradle.kts
Labels: size/M

#1157 Make `build.sh` work with `sh`
  pkg/info/build.sh
Labels: size/XS

#1161 Update query for rate limit dashboard
  blueprints/examples/static-rate-limiting/gen/dashboards/example.json
  blueprints/lib/1.0/blueprints/static-rate-limiting/dashboard.libsonnet
Labels: size/XS

#1159 Add logical combinator components
  api/aperture/policy/language/v1/policy.proto
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.go
  api/gen/proto/go/aperture/policy/language/v1/policy.pb.json.go
  api/gen/proto/go/aperture/policy/language/v1/policy_deepcopy.gen.go
  blueprints/lib/1.0/_gen/v1/and.libsonnet
  blueprints/lib/1.0/_gen/v1/andins.libsonnet
  blueprints/lib/1.0/_gen/v1/andouts.libsonnet
  blueprints/lib/1.0/_gen/v1/component.libsonnet
  blueprints/lib/1.0/_gen/v1/gen.libsonnet
  blueprints/lib/1.0/_gen/v1/inverter.libsonnet
  blueprints/lib/1.0/_gen/v1/inverterins.libsonnet
  blueprints/lib/1.0/_gen/v1/inverterouts.libsonnet
  blueprints/lib/1.0/_gen/v1/or.libsonnet
  blueprints/lib/1.0/_gen/v1/orins.libsonnet
  blueprints/lib/1.0/_gen/v1/orouts.libsonnet
  docs/content/assets/openapiv2/aperture-controller.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  docs/content/references/configuration/policy.md
  docs/gen/policy/policy.yaml
  pkg/policies/controlplane/circuitfactory/component-factory.go
  pkg/policies/controlplane/components/logical.go
  pkg/policies/controlplane/components/logical_test.go
  pkg/policies/controlplane/components/tristate/tristate.go
Labels: size/XXL

#1162 Provide a proper link to java agent download
  docs/content/get-started/flow-control/sdk/java/auto-instrumentation.md
Labels: size/XS

#1158 Added API for fetching stats from the olric cluster
  api/aperture/distcache/v1/stats.proto
  api/buf.lock
  api/gen/proto/go/aperture/distcache/v1/stats.pb.go
  api/gen/proto/go/aperture/distcache/v1/stats.pb.gw.go
  api/gen/proto/go/aperture/distcache/v1/stats.pb.json.go
  api/gen/proto/go/aperture/distcache/v1/stats_deepcopy.gen.go
  api/gen/proto/go/aperture/distcache/v1/stats_grpc.pb.go
  docs/content/assets/openapiv2/aperture-agent.swagger.yaml
  docs/content/assets/openapiv2/aperture.swagger.yaml
  pkg/distcache/provider.go
  pkg/distcache/stats-service.go
Labels: size/L

#1160 Change import file name from introduction.md to apertureVersion.js
  blueprints/scripts/generate_all.sh
  docs/content/apertureVersion.js
  docs/content/concepts/flow-control/flow-control.md
  docs/content/get-started/flow-control/sdk/overview.md
  docs/content/get-started/installation/agent/bare_metal.md
  docs/content/get-started/policies/applying-policies.md
  docs/content/get-started/policies/blueprints.md
  docs/content/introduction.md
  docs/content/references/bundled-blueprints/latency-gradient-concurrency-limiting.md
  docs/content/references/bundled-blueprints/signals-dashboard.md
  docs/content/references/bundled-blueprints/static-rate-limiting.md
Labels: size/S

#1166 Moved policy as a separate app under playground
  playground/Tiltfile
  playground/tanka/apps/aperture-controller/mixins.libsonnet
  playground/tanka/apps/policy/main.jsonnet
  playground/tanka/apps/policy/mixins.libsonnet
  playground/tanka/jsonnetfile.json
  playground/tanka/jsonnetfile.lock.json
Labels: size/L

#1168 Add UT for PulseGenerator
  pkg/policies/controlplane/components/pulse-generator_test.go
Labels: size/M
